# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'single2overlapInterface.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_single2overlap(object):
    def setupUi(self, single2overlap):
        single2overlap.setObjectName("single2overlap")
        single2overlap.setWindowModality(QtCore.Qt.WindowModal)
        single2overlap.resize(1533, 803)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(single2overlap.sizePolicy().hasHeightForWidth())
        single2overlap.setSizePolicy(sizePolicy)
        single2overlap.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.gridLayout = QtWidgets.QGridLayout(single2overlap)
        self.gridLayout.setObjectName("gridLayout")
        self.mainLayout = QtWidgets.QGridLayout()
        self.mainLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.mainLayout.setObjectName("mainLayout")
        self.infoTitle = QtWidgets.QLabel(single2overlap)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.infoTitle.sizePolicy().hasHeightForWidth())
        self.infoTitle.setSizePolicy(sizePolicy)
        self.infoTitle.setObjectName("infoTitle")
        self.mainLayout.addWidget(self.infoTitle, 0, 0, 1, 1)
        self.fishSelector = QtWidgets.QGroupBox(single2overlap)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.fishSelector.sizePolicy().hasHeightForWidth())
        self.fishSelector.setSizePolicy(sizePolicy)
        self.fishSelector.setTitle("")
        self.fishSelector.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.fishSelector.setObjectName("fishSelector")
        self.layoutWidget = QtWidgets.QWidget(self.fishSelector)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 252, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.fishSelectorLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.fishSelectorLayout.setContentsMargins(0, 0, 0, 0)
        self.fishSelectorLayout.setObjectName("fishSelectorLayout")
        self.fishAButton = QtWidgets.QRadioButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fishAButton.sizePolicy().hasHeightForWidth())
        self.fishAButton.setSizePolicy(sizePolicy)
        self.fishAButton.setObjectName("fishAButton")
        self.fishSelectorLayout.addWidget(self.fishAButton)
        self.fishBButton = QtWidgets.QRadioButton(self.layoutWidget)
        self.fishBButton.setObjectName("fishBButton")
        self.fishSelectorLayout.addWidget(self.fishBButton)
        self.mainLayout.addWidget(self.fishSelector, 0, 1, 1, 1)
        self.graphsLayout = QtWidgets.QHBoxLayout()
        self.graphsLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.graphsLayout.setObjectName("graphsLayout")
        self.prevLayout = QtWidgets.QVBoxLayout()
        self.prevLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.prevLayout.setObjectName("prevLayout")
        self.prev1 = singleSignal(single2overlap)
        self.prev1.setObjectName("prev1")
        self.prevLayout.addWidget(self.prev1)
        self.prev2 = singleSignal(single2overlap)
        self.prev2.setObjectName("prev2")
        self.prevLayout.addWidget(self.prev2)
        self.graphsLayout.addLayout(self.prevLayout)
        self.spikeLayout = QtWidgets.QVBoxLayout()
        self.spikeLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.spikeLayout.setObjectName("spikeLayout")
        self.spike = singleSignal(single2overlap)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.spike.sizePolicy().hasHeightForWidth())
        self.spike.setSizePolicy(sizePolicy)
        self.spike.setObjectName("spike")
        self.spikeLayout.addWidget(self.spike)
        self.graphsLayout.addLayout(self.spikeLayout)
        self.nextLayout = QtWidgets.QVBoxLayout()
        self.nextLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.nextLayout.setObjectName("nextLayout")
        self.next1 = singleSignal(single2overlap)
        self.next1.setObjectName("next1")
        self.nextLayout.addWidget(self.next1)
        self.next2 = singleSignal(single2overlap)
        self.next2.setObjectName("next2")
        self.nextLayout.addWidget(self.next2)
        self.graphsLayout.addLayout(self.nextLayout)
        self.mainLayout.addLayout(self.graphsLayout, 1, 0, 1, 3)
        self.bottomLayout = QtWidgets.QHBoxLayout()
        self.bottomLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.bottomLayout.setObjectName("bottomLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout.setContentsMargins(-1, 10, -1, 10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.channelLabel = QtWidgets.QLabel(single2overlap)
        self.channelLabel.setObjectName("channelLabel")
        self.verticalLayout.addWidget(self.channelLabel)
        self.channelNumber = QtWidgets.QLabel(single2overlap)
        self.channelNumber.setObjectName("channelNumber")
        self.verticalLayout.addWidget(self.channelNumber)
        self.bottomLayout.addLayout(self.verticalLayout)
        self.channelSelector = QtWidgets.QSlider(single2overlap)
        self.channelSelector.setOrientation(QtCore.Qt.Horizontal)
        self.channelSelector.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.channelSelector.setObjectName("channelSelector")
        self.bottomLayout.addWidget(self.channelSelector)
        self.buttonsLayout = QtWidgets.QHBoxLayout()
        self.buttonsLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.buttonsLayout.setObjectName("buttonsLayout")
        self.okButton = QtWidgets.QPushButton(single2overlap)
        self.okButton.setObjectName("okButton")
        self.buttonsLayout.addWidget(self.okButton)
        self.cancelButton = QtWidgets.QPushButton(single2overlap)
        self.cancelButton.setObjectName("cancelButton")
        self.buttonsLayout.addWidget(self.cancelButton)
        self.bottomLayout.addLayout(self.buttonsLayout)
        self.mainLayout.addLayout(self.bottomLayout, 2, 0, 1, 3)
        self.mainLayout.setRowMinimumHeight(0, 40)
        self.mainLayout.setRowMinimumHeight(2, 80)
        self.mainLayout.setRowStretch(0, 1)
        self.mainLayout.setRowStretch(1, 20)
        self.mainLayout.setRowStretch(2, 1)
        self.gridLayout.addLayout(self.mainLayout, 0, 0, 1, 1)

        self.retranslateUi(single2overlap)
        QtCore.QMetaObject.connectSlotsByName(single2overlap)

    def retranslateUi(self, single2overlap):
        _translate = QtCore.QCoreApplication.translate
        single2overlap.setWindowTitle(_translate("single2overlap", "IPI and SVM tool"))
        self.infoTitle.setText(_translate("single2overlap", "Select the instant of the spike for fish:"))
        self.fishAButton.setText(_translate("single2overlap", "Fish A"))
        self.fishBButton.setText(_translate("single2overlap", "Fish B"))
        self.channelLabel.setText(_translate("single2overlap", "Channel"))
        self.channelNumber.setText(_translate("single2overlap", "TextLabel"))
        self.okButton.setText(_translate("single2overlap", "Ok"))
        self.cancelButton.setText(_translate("single2overlap", "Cancel"))

from single2overlapAux import singleSignal
