# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'discriminate_interface.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_discriminateWindow(object):
    def setupUi(self, discriminateWindow):
        discriminateWindow.setObjectName("discriminateWindow")
        discriminateWindow.setWindowModality(QtCore.Qt.WindowModal)
        discriminateWindow.resize(1117, 896)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(discriminateWindow.sizePolicy().hasHeightForWidth())
        discriminateWindow.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(discriminateWindow)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(discriminateWindow)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -68, 1085, 946))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.step3Layout = QtWidgets.QVBoxLayout()
        self.step3Layout.setObjectName("step3Layout")
        self.step3TitleLabel = ClickQLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.step3TitleLabel.setFont(font)
        self.step3TitleLabel.setObjectName("step3TitleLabel")
        self.step3Layout.addWidget(self.step3TitleLabel)
        self.step3ParametersLayout = QtWidgets.QGridLayout()
        self.step3ParametersLayout.setObjectName("step3ParametersLayout")
        self.saveSinglefishLineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.saveSinglefishLineEdit.setObjectName("saveSinglefishLineEdit")
        self.step3ParametersLayout.addWidget(self.saveSinglefishLineEdit, 7, 1, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.step3ParametersLayout.addItem(spacerItem, 6, 0, 1, 3)
        self.loadSpikesLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.loadSpikesLabel.setObjectName("loadSpikesLabel")
        self.step3ParametersLayout.addWidget(self.loadSpikesLabel, 0, 0, 1, 1)
        self.verifySpikesBut = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.verifySpikesBut.setObjectName("verifySpikesBut")
        self.step3ParametersLayout.addWidget(self.verifySpikesBut, 1, 0, 1, 3)
        self.saveSinglefishLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.saveSinglefishLabel.setObjectName("saveSinglefishLabel")
        self.step3ParametersLayout.addWidget(self.saveSinglefishLabel, 7, 0, 1, 1)
        self.loadSVMModelLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.loadSVMModelLabel.setObjectName("loadSVMModelLabel")
        self.step3ParametersLayout.addWidget(self.loadSVMModelLabel, 5, 0, 1, 1)
        self.loadFilterLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.loadFilterLabel.setObjectName("loadFilterLabel")
        self.step3ParametersLayout.addWidget(self.loadFilterLabel, 3, 0, 1, 1)
        self.loadRescaleLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.loadRescaleLabel.setObjectName("loadRescaleLabel")
        self.step3ParametersLayout.addWidget(self.loadRescaleLabel, 4, 0, 1, 1)
        self.saveProbLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.saveProbLabel.setObjectName("saveProbLabel")
        self.step3ParametersLayout.addWidget(self.saveProbLabel, 8, 0, 1, 1)
        self.loadFilterLineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.loadFilterLineEdit.setObjectName("loadFilterLineEdit")
        self.step3ParametersLayout.addWidget(self.loadFilterLineEdit, 3, 1, 1, 2)
        self.loadRescaleLineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.loadRescaleLineEdit.setObjectName("loadRescaleLineEdit")
        self.step3ParametersLayout.addWidget(self.loadRescaleLineEdit, 4, 1, 1, 2)
        self.loadSVMModelLineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.loadSVMModelLineEdit.setText("")
        self.loadSVMModelLineEdit.setObjectName("loadSVMModelLineEdit")
        self.step3ParametersLayout.addWidget(self.loadSVMModelLineEdit, 5, 1, 1, 2)
        self.applySVMBut = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.applySVMBut.setObjectName("applySVMBut")
        self.step3ParametersLayout.addWidget(self.applySVMBut, 11, 0, 1, 3)
        self.saveProbLineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.saveProbLineEdit.setObjectName("saveProbLineEdit")
        self.step3ParametersLayout.addWidget(self.saveProbLineEdit, 8, 1, 1, 2)
        self.loadSpikesLineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.loadSpikesLineEdit.setObjectName("loadSpikesLineEdit")
        self.step3ParametersLayout.addWidget(self.loadSpikesLineEdit, 0, 1, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.step3ParametersLayout.addItem(spacerItem1, 2, 0, 1, 3)
        self.minWinLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.minWinLabel.setObjectName("minWinLabel")
        self.step3ParametersLayout.addWidget(self.minWinLabel, 9, 0, 1, 1)
        self.minWinLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.minWinLineEdit.setObjectName("minWinLineEdit")
        self.step3ParametersLayout.addWidget(self.minWinLineEdit, 9, 1, 1, 2)
        self.onlyAboveLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.onlyAboveLabel.setObjectName("onlyAboveLabel")
        self.step3ParametersLayout.addWidget(self.onlyAboveLabel, 10, 0, 1, 1)
        self.onlyAboveLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.onlyAboveLineEdit.setObjectName("onlyAboveLineEdit")
        self.step3ParametersLayout.addWidget(self.onlyAboveLineEdit, 10, 1, 1, 2)
        self.step3Layout.addLayout(self.step3ParametersLayout)
        self.gridLayout_2.addLayout(self.step3Layout, 4, 2, 1, 1)
        self.step2Layout = QtWidgets.QVBoxLayout()
        self.step2Layout.setObjectName("step2Layout")
        self.step2TitleLabel = ClickQLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.step2TitleLabel.setFont(font)
        self.step2TitleLabel.setObjectName("step2TitleLabel")
        self.step2Layout.addWidget(self.step2TitleLabel)
        self.step2ParametersLayout = QtWidgets.QGridLayout()
        self.step2ParametersLayout.setObjectName("step2ParametersLayout")
        self.tapsLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.tapsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.tapsLabel.setObjectName("tapsLabel")
        self.step2ParametersLayout.addWidget(self.tapsLabel, 6, 0, 1, 1)
        self.saveSpikesLineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.saveSpikesLineEdit.setObjectName("saveSpikesLineEdit")
        self.step2ParametersLayout.addWidget(self.saveSpikesLineEdit, 13, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.step2ParametersLayout.addItem(spacerItem2, 15, 0, 1, 2)
        self.tapsLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.tapsLineEdit.setObjectName("tapsLineEdit")
        self.step2ParametersLayout.addWidget(self.tapsLineEdit, 6, 1, 1, 1)
        self.thresholdLevelLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.thresholdLevelLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.thresholdLevelLabel.setObjectName("thresholdLevelLabel")
        self.step2ParametersLayout.addWidget(self.thresholdLevelLabel, 9, 0, 1, 1)
        self.filterLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setBold(True)
        font.setWeight(75)
        self.filterLabel.setFont(font)
        self.filterLabel.setObjectName("filterLabel")
        self.step2ParametersLayout.addWidget(self.filterLabel, 5, 0, 1, 1)
        self.detectSpikesBut = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.detectSpikesBut.setObjectName("detectSpikesBut")
        self.step2ParametersLayout.addWidget(self.detectSpikesBut, 14, 0, 1, 2)
        self.thresholdLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setBold(True)
        font.setWeight(75)
        self.thresholdLabel.setFont(font)
        self.thresholdLabel.setObjectName("thresholdLabel")
        self.step2ParametersLayout.addWidget(self.thresholdLabel, 8, 0, 1, 1)
        self.thresholdLevelLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.thresholdLevelLineEdit.setObjectName("thresholdLevelLineEdit")
        self.step2ParametersLayout.addWidget(self.thresholdLevelLineEdit, 9, 1, 1, 1)
        self.cutoffLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.cutoffLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.cutoffLabel.setObjectName("cutoffLabel")
        self.step2ParametersLayout.addWidget(self.cutoffLabel, 7, 0, 1, 1)
        self.refracLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.refracLabel.setObjectName("refracLabel")
        self.step2ParametersLayout.addWidget(self.refracLabel, 10, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.saveSpikesLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.saveSpikesLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.saveSpikesLabel.setObjectName("saveSpikesLabel")
        self.step2ParametersLayout.addWidget(self.saveSpikesLabel, 13, 0, 1, 1)
        self.cutoffLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.cutoffLineEdit.setObjectName("cutoffLineEdit")
        self.step2ParametersLayout.addWidget(self.cutoffLineEdit, 7, 1, 1, 1)
        self.saveLoadHilbLineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.saveLoadHilbLineEdit.setObjectName("saveLoadHilbLineEdit")
        self.step2ParametersLayout.addWidget(self.saveLoadHilbLineEdit, 3, 1, 1, 1)
        self.hilbLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.hilbLabel.setFont(font)
        self.hilbLabel.setObjectName("hilbLabel")
        self.step2ParametersLayout.addWidget(self.hilbLabel, 2, 0, 1, 1)
        self.useHilbLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.useHilbLabel.setObjectName("useHilbLabel")
        self.step2ParametersLayout.addWidget(self.useHilbLabel, 4, 0, 1, 1)
        self.saveLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.saveLabel.setFont(font)
        self.saveLabel.setObjectName("saveLabel")
        self.step2ParametersLayout.addWidget(self.saveLabel, 12, 0, 1, 1)
        self.useHilbCheckBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.useHilbCheckBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.useHilbCheckBox.setText("")
        self.useHilbCheckBox.setObjectName("useHilbCheckBox")
        self.step2ParametersLayout.addWidget(self.useHilbCheckBox, 4, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.saveLoadHilbLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.saveLoadHilbLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.saveLoadHilbLabel.setObjectName("saveLoadHilbLabel")
        self.step2ParametersLayout.addWidget(self.saveLoadHilbLabel, 3, 0, 1, 1)
        self.maxSizeLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.maxSizeLabel.setObjectName("maxSizeLabel")
        self.step2ParametersLayout.addWidget(self.maxSizeLabel, 11, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.refractoryLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.refractoryLineEdit.setObjectName("refractoryLineEdit")
        self.step2ParametersLayout.addWidget(self.refractoryLineEdit, 10, 1, 1, 1)
        self.maxSizeLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.maxSizeLineEdit.setObjectName("maxSizeLineEdit")
        self.step2ParametersLayout.addWidget(self.maxSizeLineEdit, 11, 1, 1, 1)
        self.chirpsLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.chirpsLabel.setFont(font)
        self.chirpsLabel.setObjectName("chirpsLabel")
        self.step2ParametersLayout.addWidget(self.chirpsLabel, 0, 0, 1, 1)
        self.loadChirpsLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.loadChirpsLabel.setObjectName("loadChirpsLabel")
        self.step2ParametersLayout.addWidget(self.loadChirpsLabel, 1, 0, 1, 1)
        self.loadChirpsLineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.loadChirpsLineEdit.setObjectName("loadChirpsLineEdit")
        self.step2ParametersLayout.addWidget(self.loadChirpsLineEdit, 1, 1, 1, 1)
        self.step2Layout.addLayout(self.step2ParametersLayout)
        self.gridLayout_2.addLayout(self.step2Layout, 4, 0, 3, 1)
        self.step4Layout = QtWidgets.QVBoxLayout()
        self.step4Layout.setObjectName("step4Layout")
        self.step4TitleLabel = ClickQLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.step4TitleLabel.setFont(font)
        self.step4TitleLabel.setObjectName("step4TitleLabel")
        self.step4Layout.addWidget(self.step4TitleLabel)
        self.step4ParametersLayout = QtWidgets.QGridLayout()
        self.step4ParametersLayout.setObjectName("step4ParametersLayout")
        self.loadProbLineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.loadProbLineEdit.setObjectName("loadProbLineEdit")
        self.step4ParametersLayout.addWidget(self.loadProbLineEdit, 1, 1, 1, 1)
        self.saveDBLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.saveDBLabel.setObjectName("saveDBLabel")
        self.step4ParametersLayout.addWidget(self.saveDBLabel, 3, 0, 1, 1)
        self.saveDBLineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.saveDBLineEdit.setObjectName("saveDBLineEdit")
        self.step4ParametersLayout.addWidget(self.saveDBLineEdit, 3, 1, 1, 1)
        self.loadProbLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.loadProbLabel.setObjectName("loadProbLabel")
        self.step4ParametersLayout.addWidget(self.loadProbLabel, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.step4ParametersLayout.addItem(spacerItem3, 2, 0, 1, 2)
        self.loadSinglefishLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.loadSinglefishLabel.setObjectName("loadSinglefishLabel")
        self.step4ParametersLayout.addWidget(self.loadSinglefishLabel, 0, 0, 1, 1)
        self.loadSinglefishLineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.loadSinglefishLineEdit.setObjectName("loadSinglefishLineEdit")
        self.step4ParametersLayout.addWidget(self.loadSinglefishLineEdit, 0, 1, 1, 1)
        self.applyContinuityBut = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.applyContinuityBut.setObjectName("applyContinuityBut")
        self.step4ParametersLayout.addWidget(self.applyContinuityBut, 4, 0, 1, 2)
        self.step4Layout.addLayout(self.step4ParametersLayout)
        self.gridLayout_2.addLayout(self.step4Layout, 9, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_2.addWidget(self.line_3, 3, 0, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_2.addWidget(self.line_6, 5, 2, 1, 1)
        self.line = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 8, 0, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_2.addWidget(self.line_5, 8, 2, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_2.addWidget(self.line_4, 9, 1, 1, 1)
        self.step5Layout = QtWidgets.QVBoxLayout()
        self.step5Layout.setObjectName("step5Layout")
        self.step5TitleLabel = ClickQLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.step5TitleLabel.setFont(font)
        self.step5TitleLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.step5TitleLabel.setObjectName("step5TitleLabel")
        self.step5Layout.addWidget(self.step5TitleLabel)
        self.step5ParametersLayout = QtWidgets.QGridLayout()
        self.step5ParametersLayout.setObjectName("step5ParametersLayout")
        self.saveTimestampsLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.saveTimestampsLabel.setObjectName("saveTimestampsLabel")
        self.step5ParametersLayout.addWidget(self.saveTimestampsLabel, 1, 0, 1, 1)
        self.loadDBLineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.loadDBLineEdit.setObjectName("loadDBLineEdit")
        self.step5ParametersLayout.addWidget(self.loadDBLineEdit, 0, 1, 1, 1)
        self.loadTimestampsLineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.loadTimestampsLineEdit.setObjectName("loadTimestampsLineEdit")
        self.step5ParametersLayout.addWidget(self.loadTimestampsLineEdit, 4, 1, 1, 1)
        self.saveTimestampsLineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.saveTimestampsLineEdit.setObjectName("saveTimestampsLineEdit")
        self.step5ParametersLayout.addWidget(self.saveTimestampsLineEdit, 1, 1, 1, 1)
        self.loadDBLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.loadDBLabel.setObjectName("loadDBLabel")
        self.step5ParametersLayout.addWidget(self.loadDBLabel, 0, 0, 1, 1)
        self.loadTimestampsLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.loadTimestampsLabel.setObjectName("loadTimestampsLabel")
        self.step5ParametersLayout.addWidget(self.loadTimestampsLabel, 4, 0, 1, 1)
        self.verifyCorrectTimestampsBut = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.verifyCorrectTimestampsBut.setObjectName("verifyCorrectTimestampsBut")
        self.step5ParametersLayout.addWidget(self.verifyCorrectTimestampsBut, 5, 0, 1, 2)
        self.detectTimestampsBut = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.detectTimestampsBut.setObjectName("detectTimestampsBut")
        self.step5ParametersLayout.addWidget(self.detectTimestampsBut, 2, 0, 1, 2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.step5ParametersLayout.addItem(spacerItem4, 3, 0, 1, 2)
        self.step5Layout.addLayout(self.step5ParametersLayout)
        self.gridLayout_2.addLayout(self.step5Layout, 9, 2, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.lowSaturationLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lowSaturationLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.lowSaturationLabel.setObjectName("lowSaturationLabel")
        self.gridLayout_6.addWidget(self.lowSaturationLabel, 1, 1, 1, 1)
        self.saturationLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setBold(False)
        font.setWeight(50)
        self.saturationLabel.setFont(font)
        self.saturationLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.saturationLabel.setObjectName("saturationLabel")
        self.gridLayout_6.addWidget(self.saturationLabel, 2, 0, 1, 1)
        self.lowSaturationLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lowSaturationLineEdit.setObjectName("lowSaturationLineEdit")
        self.gridLayout_6.addWidget(self.lowSaturationLineEdit, 2, 1, 1, 1)
        self.highSaturationLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.highSaturationLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.highSaturationLabel.setObjectName("highSaturationLabel")
        self.gridLayout_6.addWidget(self.highSaturationLabel, 1, 2, 1, 1)
        self.highSaturationLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.highSaturationLineEdit.setObjectName("highSaturationLineEdit")
        self.gridLayout_6.addWidget(self.highSaturationLineEdit, 2, 2, 1, 1)
        self.loadTimeseriesLineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.loadTimeseriesLineEdit.setObjectName("loadTimeseriesLineEdit")
        self.gridLayout_6.addWidget(self.loadTimeseriesLineEdit, 0, 1, 1, 2)
        self.loadTimeseriesLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.loadTimeseriesLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.loadTimeseriesLabel.setObjectName("loadTimeseriesLabel")
        self.gridLayout_6.addWidget(self.loadTimeseriesLabel, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_6, 1, 0, 1, 3)
        self.saveLoadParametersLayout = QtWidgets.QHBoxLayout()
        self.saveLoadParametersLayout.setObjectName("saveLoadParametersLayout")
        self.saveParametersBut = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.saveParametersBut.setObjectName("saveParametersBut")
        self.saveLoadParametersLayout.addWidget(self.saveParametersBut)
        self.loadParametersBut = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.loadParametersBut.setObjectName("loadParametersBut")
        self.saveLoadParametersLayout.addWidget(self.loadParametersBut)
        self.gridLayout_2.addLayout(self.saveLoadParametersLayout, 0, 0, 1, 3)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/Logos/LogoClaro_comLogo_w580.png"))
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 7, 2, 1, 1)
        self.step1Layout = QtWidgets.QVBoxLayout()
        self.step1Layout.setObjectName("step1Layout")
        self.step1TitleLabel = ClickQLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.step1TitleLabel.setFont(font)
        self.step1TitleLabel.setObjectName("step1TitleLabel")
        self.step1Layout.addWidget(self.step1TitleLabel)
        self.step1ParametersLayout = QtWidgets.QGridLayout()
        self.step1ParametersLayout.setObjectName("step1ParametersLayout")
        self.saveChirpsLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.saveChirpsLabel.setObjectName("saveChirpsLabel")
        self.step1ParametersLayout.addWidget(self.saveChirpsLabel, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.loadChirpsModelLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.loadChirpsModelLabel.setObjectName("loadChirpsModelLabel")
        self.step1ParametersLayout.addWidget(self.loadChirpsModelLabel, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.loadChirpsModelLineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.loadChirpsModelLineEdit.setObjectName("loadChirpsModelLineEdit")
        self.step1ParametersLayout.addWidget(self.loadChirpsModelLineEdit, 0, 1, 1, 1)
        self.saveChirpsLineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.saveChirpsLineEdit.setObjectName("saveChirpsLineEdit")
        self.step1ParametersLayout.addWidget(self.saveChirpsLineEdit, 1, 1, 1, 1)
        self.detectChirpsBut = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.detectChirpsBut.setObjectName("detectChirpsBut")
        self.step1ParametersLayout.addWidget(self.detectChirpsBut, 2, 0, 1, 2)
        self.step1Layout.addLayout(self.step1ParametersLayout)
        self.gridLayout_2.addLayout(self.step1Layout, 2, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 2, 1, 6, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(discriminateWindow)
        QtCore.QMetaObject.connectSlotsByName(discriminateWindow)
        discriminateWindow.setTabOrder(self.scrollArea, self.saveParametersBut)
        discriminateWindow.setTabOrder(self.saveParametersBut, self.loadParametersBut)
        discriminateWindow.setTabOrder(self.loadParametersBut, self.loadTimeseriesLineEdit)
        discriminateWindow.setTabOrder(self.loadTimeseriesLineEdit, self.lowSaturationLineEdit)
        discriminateWindow.setTabOrder(self.lowSaturationLineEdit, self.highSaturationLineEdit)
        discriminateWindow.setTabOrder(self.highSaturationLineEdit, self.tapsLineEdit)
        discriminateWindow.setTabOrder(self.tapsLineEdit, self.cutoffLineEdit)
        discriminateWindow.setTabOrder(self.cutoffLineEdit, self.thresholdLevelLineEdit)
        discriminateWindow.setTabOrder(self.thresholdLevelLineEdit, self.saveSpikesLineEdit)
        discriminateWindow.setTabOrder(self.saveSpikesLineEdit, self.detectSpikesBut)
        discriminateWindow.setTabOrder(self.detectSpikesBut, self.loadSpikesLineEdit)
        discriminateWindow.setTabOrder(self.loadSpikesLineEdit, self.verifySpikesBut)
        discriminateWindow.setTabOrder(self.verifySpikesBut, self.loadFilterLineEdit)
        discriminateWindow.setTabOrder(self.loadFilterLineEdit, self.loadRescaleLineEdit)
        discriminateWindow.setTabOrder(self.loadRescaleLineEdit, self.loadSVMModelLineEdit)
        discriminateWindow.setTabOrder(self.loadSVMModelLineEdit, self.saveSinglefishLineEdit)
        discriminateWindow.setTabOrder(self.saveSinglefishLineEdit, self.saveProbLineEdit)
        discriminateWindow.setTabOrder(self.saveProbLineEdit, self.minWinLineEdit)
        discriminateWindow.setTabOrder(self.minWinLineEdit, self.applySVMBut)
        discriminateWindow.setTabOrder(self.applySVMBut, self.loadSinglefishLineEdit)
        discriminateWindow.setTabOrder(self.loadSinglefishLineEdit, self.loadProbLineEdit)
        discriminateWindow.setTabOrder(self.loadProbLineEdit, self.saveDBLineEdit)
        discriminateWindow.setTabOrder(self.saveDBLineEdit, self.applyContinuityBut)
        discriminateWindow.setTabOrder(self.applyContinuityBut, self.loadDBLineEdit)
        discriminateWindow.setTabOrder(self.loadDBLineEdit, self.saveTimestampsLineEdit)
        discriminateWindow.setTabOrder(self.saveTimestampsLineEdit, self.detectTimestampsBut)
        discriminateWindow.setTabOrder(self.detectTimestampsBut, self.loadTimestampsLineEdit)
        discriminateWindow.setTabOrder(self.loadTimestampsLineEdit, self.verifyCorrectTimestampsBut)

    def retranslateUi(self, discriminateWindow):
        _translate = QtCore.QCoreApplication.translate
        discriminateWindow.setWindowTitle(_translate("discriminateWindow", "gymnotools - Discriminate"))
        self.step3TitleLabel.setText(_translate("discriminateWindow", "3. Apply SVM >"))
        self.loadSpikesLabel.setText(_translate("discriminateWindow", "Load spikes file:"))
        self.verifySpikesBut.setText(_translate("discriminateWindow", "Verify detection"))
        self.saveSinglefishLabel.setText(_translate("discriminateWindow", "Save SVM timestamps (singlefish) as:"))
        self.loadSVMModelLabel.setText(_translate("discriminateWindow", "Load training SVM model:"))
        self.loadFilterLabel.setText(_translate("discriminateWindow", "Load training filter file:"))
        self.loadRescaleLabel.setText(_translate("discriminateWindow", "Load training rescale file:"))
        self.saveProbLabel.setText(_translate("discriminateWindow", "Save probabilities as:"))
        self.applySVMBut.setText(_translate("discriminateWindow", "Apply SVM"))
        self.minWinLabel.setText(_translate("discriminateWindow", "Minimum windows needed to analyze with SVM:"))
        self.minWinLineEdit.setText(_translate("discriminateWindow", "2"))
        self.onlyAboveLabel.setText(_translate("discriminateWindow", "Only apply on spikes above (V) (same used for training):"))
        self.step2TitleLabel.setText(_translate("discriminateWindow", "2. Select parameters and detect spikes >"))
        self.tapsLabel.setText(_translate("discriminateWindow", "Number of taps:"))
        self.tapsLineEdit.setText(_translate("discriminateWindow", "301"))
        self.thresholdLevelLabel.setText(_translate("discriminateWindow", "Threshold level (V):"))
        self.filterLabel.setText(_translate("discriminateWindow", "Low-pass filter parameters:"))
        self.detectSpikesBut.setText(_translate("discriminateWindow", "Detect Spikes"))
        self.thresholdLabel.setText(_translate("discriminateWindow", "Threshold:"))
        self.thresholdLevelLineEdit.setText(_translate("discriminateWindow", "1.0"))
        self.cutoffLabel.setText(_translate("discriminateWindow", "Cutoff frequency (cycles/sample):"))
        self.refracLabel.setText(_translate("discriminateWindow", "Refractory period (s):"))
        self.saveSpikesLabel.setText(_translate("discriminateWindow", "Save detected spikes as: "))
        self.cutoffLineEdit.setText(_translate("discriminateWindow", "1.0"))
        self.hilbLabel.setText(_translate("discriminateWindow", "Hilbert Transform:"))
        self.useHilbLabel.setText(_translate("discriminateWindow", "Use existing Hilbert Transform File?"))
        self.saveLabel.setText(_translate("discriminateWindow", "Save:"))
        self.saveLoadHilbLabel.setText(_translate("discriminateWindow", "Save/Load hilbert Transform:"))
        self.maxSizeLabel.setText(_translate("discriminateWindow", "Maximum size (s):"))
        self.chirpsLabel.setText(_translate("discriminateWindow", "Chirps:"))
        self.loadChirpsLabel.setText(_translate("discriminateWindow", "Load chirps file:"))
        self.step4TitleLabel.setText(_translate("discriminateWindow", "4. Apply continuity criteria >"))
        self.saveDBLabel.setText(_translate("discriminateWindow", "Save DataBase as:"))
        self.loadProbLabel.setText(_translate("discriminateWindow", "Load probabilities:"))
        self.loadSinglefishLabel.setText(_translate("discriminateWindow", "Load SVM timestamps (singlefish):"))
        self.applyContinuityBut.setText(_translate("discriminateWindow", "Apply continuity"))
        self.step5TitleLabel.setText(_translate("discriminateWindow", "4. Detect zero-crossing timestamps >"))
        self.saveTimestampsLabel.setText(_translate("discriminateWindow", "Save timetamps as:"))
        self.loadDBLabel.setText(_translate("discriminateWindow", "Load DataBase:"))
        self.loadTimestampsLabel.setText(_translate("discriminateWindow", "Load timestamps:"))
        self.verifyCorrectTimestampsBut.setText(_translate("discriminateWindow", "Verify and Manually correct timestamps (Timeseries file needed!)"))
        self.detectTimestampsBut.setText(_translate("discriminateWindow", "Detect timestamps"))
        self.lowSaturationLabel.setText(_translate("discriminateWindow", "LOW saturation level (V):"))
        self.saturationLabel.setText(_translate("discriminateWindow", "Saturation level:"))
        self.highSaturationLabel.setText(_translate("discriminateWindow", "HIGH saturation level (V):"))
        self.loadTimeseriesLabel.setText(_translate("discriminateWindow", "Load timeseries data:"))
        self.saveParametersBut.setText(_translate("discriminateWindow", "Save parameters"))
        self.loadParametersBut.setText(_translate("discriminateWindow", "Load parameters"))
        self.step1TitleLabel.setText(_translate("discriminateWindow", "1. Detect chirps >"))
        self.saveChirpsLabel.setText(_translate("discriminateWindow", "Save chirps file:"))
        self.loadChirpsModelLabel.setText(_translate("discriminateWindow", "Load chirps model:"))
        self.detectChirpsBut.setText(_translate("discriminateWindow", "detectChirps"))

from clickAux import ClickQLabel, ClickQLineEdit
import resource_rc
