# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'training_interface.ui'
#
# Created: Mon May 18 19:05:32 2015
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_trainingWindow(object):
    def setupUi(self, trainingWindow):
        trainingWindow.setObjectName(_fromUtf8("trainingWindow"))
        trainingWindow.setWindowModality(QtCore.Qt.WindowModal)
        trainingWindow.resize(1124, 1051)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(trainingWindow.sizePolicy().hasHeightForWidth())
        trainingWindow.setSizePolicy(sizePolicy)
        self.gridLayout = QtGui.QGridLayout(trainingWindow)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.scrollArea = QtGui.QScrollArea(trainingWindow)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1106, 1033))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_2 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.saveLoadParametersLayout = QtGui.QHBoxLayout()
        self.saveLoadParametersLayout.setObjectName(_fromUtf8("saveLoadParametersLayout"))
        self.saveParametersBut = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.saveParametersBut.setObjectName(_fromUtf8("saveParametersBut"))
        self.saveLoadParametersLayout.addWidget(self.saveParametersBut)
        self.loadParametersBut = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.loadParametersBut.setObjectName(_fromUtf8("loadParametersBut"))
        self.saveLoadParametersLayout.addWidget(self.loadParametersBut)
        self.gridLayout_2.addLayout(self.saveLoadParametersLayout, 0, 0, 1, 5)
        self.step1Layout = QtGui.QVBoxLayout()
        self.step1Layout.setObjectName(_fromUtf8("step1Layout"))
        self.step1TitleLabel = clickQLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.step1TitleLabel.setFont(font)
        self.step1TitleLabel.setObjectName(_fromUtf8("step1TitleLabel"))
        self.step1Layout.addWidget(self.step1TitleLabel)
        self.step1ParametersLayout = QtGui.QGridLayout()
        self.step1ParametersLayout.setObjectName(_fromUtf8("step1ParametersLayout"))
        self.cutoff2LineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.cutoff2LineEdit.setObjectName(_fromUtf8("cutoff2LineEdit"))
        self.step1ParametersLayout.addWidget(self.cutoff2LineEdit, 8, 2, 1, 1)
        self.thresholdAssist2But = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.thresholdAssist2But.setObjectName(_fromUtf8("thresholdAssist2But"))
        self.step1ParametersLayout.addWidget(self.thresholdAssist2But, 10, 2, 1, 1)
        self.spikeParametersFish1Label = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.spikeParametersFish1Label.setAlignment(QtCore.Qt.AlignCenter)
        self.spikeParametersFish1Label.setObjectName(_fromUtf8("spikeParametersFish1Label"))
        self.step1ParametersLayout.addWidget(self.spikeParametersFish1Label, 0, 1, 1, 1)
        self.saturationLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setBold(True)
        font.setWeight(75)
        self.saturationLabel.setFont(font)
        self.saturationLabel.setObjectName(_fromUtf8("saturationLabel"))
        self.step1ParametersLayout.addWidget(self.saturationLabel, 2, 0, 1, 1)
        self.cutoff1LineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.cutoff1LineEdit.setObjectName(_fromUtf8("cutoff1LineEdit"))
        self.step1ParametersLayout.addWidget(self.cutoff1LineEdit, 8, 1, 1, 1)
        self.lowSaturation1LineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lowSaturation1LineEdit.setObjectName(_fromUtf8("lowSaturation1LineEdit"))
        self.step1ParametersLayout.addWidget(self.lowSaturation1LineEdit, 3, 1, 1, 1)
        self.taps1LineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.taps1LineEdit.setObjectName(_fromUtf8("taps1LineEdit"))
        self.step1ParametersLayout.addWidget(self.taps1LineEdit, 7, 1, 1, 1)
        self.loadTS1LineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.loadTS1LineEdit.setObjectName(_fromUtf8("loadTS1LineEdit"))
        self.step1ParametersLayout.addWidget(self.loadTS1LineEdit, 1, 1, 1, 1)
        self.thresholdLevel1LineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.thresholdLevel1LineEdit.setObjectName(_fromUtf8("thresholdLevel1LineEdit"))
        self.step1ParametersLayout.addWidget(self.thresholdLevel1LineEdit, 11, 1, 1, 1)
        self.highSaturation1LineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.highSaturation1LineEdit.setObjectName(_fromUtf8("highSaturation1LineEdit"))
        self.step1ParametersLayout.addWidget(self.highSaturation1LineEdit, 4, 1, 1, 1)
        self.thresholdLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setBold(True)
        font.setWeight(75)
        self.thresholdLabel.setFont(font)
        self.thresholdLabel.setObjectName(_fromUtf8("thresholdLabel"))
        self.step1ParametersLayout.addWidget(self.thresholdLabel, 9, 0, 1, 1)
        self.filterLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setBold(True)
        font.setWeight(75)
        self.filterLabel.setFont(font)
        self.filterLabel.setObjectName(_fromUtf8("filterLabel"))
        self.step1ParametersLayout.addWidget(self.filterLabel, 5, 0, 1, 1)
        self.loadTS2LineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.loadTS2LineEdit.setObjectName(_fromUtf8("loadTS2LineEdit"))
        self.step1ParametersLayout.addWidget(self.loadTS2LineEdit, 1, 2, 1, 1)
        self.thresholdLevelLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.thresholdLevelLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.thresholdLevelLabel.setObjectName(_fromUtf8("thresholdLevelLabel"))
        self.step1ParametersLayout.addWidget(self.thresholdLevelLabel, 11, 0, 1, 1)
        self.filterAssist2But = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.filterAssist2But.setObjectName(_fromUtf8("filterAssist2But"))
        self.step1ParametersLayout.addWidget(self.filterAssist2But, 6, 2, 1, 1)
        self.taps2LineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.taps2LineEdit.setObjectName(_fromUtf8("taps2LineEdit"))
        self.step1ParametersLayout.addWidget(self.taps2LineEdit, 7, 2, 1, 1)
        self.spikeParametersFish2Label = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.spikeParametersFish2Label.setAlignment(QtCore.Qt.AlignCenter)
        self.spikeParametersFish2Label.setObjectName(_fromUtf8("spikeParametersFish2Label"))
        self.step1ParametersLayout.addWidget(self.spikeParametersFish2Label, 0, 2, 1, 1)
        self.lowSaturation2LineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lowSaturation2LineEdit.setObjectName(_fromUtf8("lowSaturation2LineEdit"))
        self.step1ParametersLayout.addWidget(self.lowSaturation2LineEdit, 3, 2, 1, 1)
        self.highSaturation2LineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.highSaturation2LineEdit.setObjectName(_fromUtf8("highSaturation2LineEdit"))
        self.step1ParametersLayout.addWidget(self.highSaturation2LineEdit, 4, 2, 1, 1)
        self.thresholdAssist1But = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.thresholdAssist1But.setObjectName(_fromUtf8("thresholdAssist1But"))
        self.step1ParametersLayout.addWidget(self.thresholdAssist1But, 10, 1, 1, 1)
        self.filterAssist1But = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.filterAssist1But.setObjectName(_fromUtf8("filterAssist1But"))
        self.step1ParametersLayout.addWidget(self.filterAssist1But, 6, 1, 1, 1)
        self.thresholdLevel2LineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.thresholdLevel2LineEdit.setObjectName(_fromUtf8("thresholdLevel2LineEdit"))
        self.step1ParametersLayout.addWidget(self.thresholdLevel2LineEdit, 11, 2, 1, 1)
        self.cutoffLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.cutoffLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.cutoffLabel.setObjectName(_fromUtf8("cutoffLabel"))
        self.step1ParametersLayout.addWidget(self.cutoffLabel, 8, 0, 1, 1)
        self.highSaturationLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.highSaturationLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.highSaturationLabel.setObjectName(_fromUtf8("highSaturationLabel"))
        self.step1ParametersLayout.addWidget(self.highSaturationLabel, 4, 0, 1, 1)
        self.lowSaturationLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lowSaturationLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.lowSaturationLabel.setObjectName(_fromUtf8("lowSaturationLabel"))
        self.step1ParametersLayout.addWidget(self.lowSaturationLabel, 3, 0, 1, 1)
        self.tapsLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.tapsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.tapsLabel.setObjectName(_fromUtf8("tapsLabel"))
        self.step1ParametersLayout.addWidget(self.tapsLabel, 7, 0, 1, 1)
        self.loadTSLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.loadTSLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.loadTSLabel.setObjectName(_fromUtf8("loadTSLabel"))
        self.step1ParametersLayout.addWidget(self.loadTSLabel, 1, 0, 1, 1)
        self.step1Layout.addLayout(self.step1ParametersLayout)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.step1Layout.addItem(spacerItem)
        self.step1Layout.setStretch(1, 4)
        self.gridLayout_2.addLayout(self.step1Layout, 2, 0, 1, 1)
        self.line_0 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.line_0.setFrameShape(QtGui.QFrame.VLine)
        self.line_0.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_0.setObjectName(_fromUtf8("line_0"))
        self.gridLayout_2.addWidget(self.line_0, 2, 1, 1, 1)
        self.step2Layout = QtGui.QVBoxLayout()
        self.step2Layout.setObjectName(_fromUtf8("step2Layout"))
        self.step2TitleLabel = clickQLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.step2TitleLabel.setFont(font)
        self.step2TitleLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.step2TitleLabel.setObjectName(_fromUtf8("step2TitleLabel"))
        self.step2Layout.addWidget(self.step2TitleLabel)
        self.step2ParametersLayout = QtGui.QGridLayout()
        self.step2ParametersLayout.setHorizontalSpacing(6)
        self.step2ParametersLayout.setVerticalSpacing(0)
        self.step2ParametersLayout.setObjectName(_fromUtf8("step2ParametersLayout"))
        self.saveSpikes2LineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.saveSpikes2LineEdit.setObjectName(_fromUtf8("saveSpikes2LineEdit"))
        self.step2ParametersLayout.addWidget(self.saveSpikes2LineEdit, 2, 2, 1, 1)
        self.verifySpikes1But = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.verifySpikes1But.setObjectName(_fromUtf8("verifySpikes1But"))
        self.step2ParametersLayout.addWidget(self.verifySpikes1But, 9, 0, 1, 2)
        self.detectSpikes1But = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.detectSpikes1But.setObjectName(_fromUtf8("detectSpikes1But"))
        self.step2ParametersLayout.addWidget(self.detectSpikes1But, 5, 0, 1, 2)
        self.saveSpikes1LineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.saveSpikes1LineEdit.setObjectName(_fromUtf8("saveSpikes1LineEdit"))
        self.step2ParametersLayout.addWidget(self.saveSpikes1LineEdit, 2, 0, 1, 2)
        self.saveWindowLengths1LineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.saveWindowLengths1LineEdit.setObjectName(_fromUtf8("saveWindowLengths1LineEdit"))
        self.step2ParametersLayout.addWidget(self.saveWindowLengths1LineEdit, 4, 0, 1, 2)
        self.loadSpikes1LineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.loadSpikes1LineEdit.setObjectName(_fromUtf8("loadSpikes1LineEdit"))
        self.step2ParametersLayout.addWidget(self.loadSpikes1LineEdit, 8, 0, 1, 2)
        self.loadSpikes2LineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.loadSpikes2LineEdit.setObjectName(_fromUtf8("loadSpikes2LineEdit"))
        self.step2ParametersLayout.addWidget(self.loadSpikes2LineEdit, 8, 2, 1, 1)
        self.saveWindowLengths2LineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.saveWindowLengths2LineEdit.setObjectName(_fromUtf8("saveWindowLengths2LineEdit"))
        self.step2ParametersLayout.addWidget(self.saveWindowLengths2LineEdit, 4, 2, 1, 1)
        self.detectSpikes2But = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.detectSpikes2But.setObjectName(_fromUtf8("detectSpikes2But"))
        self.step2ParametersLayout.addWidget(self.detectSpikes2But, 5, 2, 1, 1)
        self.detectFish2Label = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.detectFish2Label.setAlignment(QtCore.Qt.AlignCenter)
        self.detectFish2Label.setObjectName(_fromUtf8("detectFish2Label"))
        self.step2ParametersLayout.addWidget(self.detectFish2Label, 0, 2, 1, 1)
        self.detectFish1Label = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.detectFish1Label.setAlignment(QtCore.Qt.AlignCenter)
        self.detectFish1Label.setObjectName(_fromUtf8("detectFish1Label"))
        self.step2ParametersLayout.addWidget(self.detectFish1Label, 0, 0, 1, 2)
        self.saveSpikesLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.saveSpikesLabel.setObjectName(_fromUtf8("saveSpikesLabel"))
        self.step2ParametersLayout.addWidget(self.saveSpikesLabel, 1, 0, 1, 3)
        self.saveWindowLengthsLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.saveWindowLengthsLabel.setObjectName(_fromUtf8("saveWindowLengthsLabel"))
        self.step2ParametersLayout.addWidget(self.saveWindowLengthsLabel, 3, 0, 1, 3)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.step2ParametersLayout.addItem(spacerItem1, 6, 0, 1, 3)
        self.loadSpikesLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.loadSpikesLabel.setObjectName(_fromUtf8("loadSpikesLabel"))
        self.step2ParametersLayout.addWidget(self.loadSpikesLabel, 7, 0, 1, 3)
        self.verifySpikes2But = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.verifySpikes2But.setObjectName(_fromUtf8("verifySpikes2But"))
        self.step2ParametersLayout.addWidget(self.verifySpikes2But, 9, 2, 1, 1)
        self.step2ParametersLayout.setColumnStretch(0, 4)
        self.step2ParametersLayout.setColumnStretch(2, 4)
        self.step2Layout.addLayout(self.step2ParametersLayout)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        self.step2Layout.addItem(spacerItem2)
        self.step2Layout.setStretch(1, 4)
        self.gridLayout_2.addLayout(self.step2Layout, 2, 2, 1, 1)
        self.line_4 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout_2.addWidget(self.line_4, 2, 3, 1, 1)
        self.step3Layout = QtGui.QVBoxLayout()
        self.step3Layout.setObjectName(_fromUtf8("step3Layout"))
        self.step3TitleLabel = clickQLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.step3TitleLabel.setFont(font)
        self.step3TitleLabel.setObjectName(_fromUtf8("step3TitleLabel"))
        self.step3Layout.addWidget(self.step3TitleLabel)
        self.step3ParametersLayout = QtGui.QGridLayout()
        self.step3ParametersLayout.setObjectName(_fromUtf8("step3ParametersLayout"))
        self.numberFeaturesLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.numberFeaturesLabel.setObjectName(_fromUtf8("numberFeaturesLabel"))
        self.step3ParametersLayout.addWidget(self.numberFeaturesLabel, 5, 0, 1, 2)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.step3ParametersLayout.addItem(spacerItem3, 9, 0, 1, 2)
        self.saveFeaturesLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.saveFeaturesLabel.setObjectName(_fromUtf8("saveFeaturesLabel"))
        self.step3ParametersLayout.addWidget(self.saveFeaturesLabel, 1, 0, 1, 2)
        self.loadFeaturesLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.loadFeaturesLabel.setObjectName(_fromUtf8("loadFeaturesLabel"))
        self.step3ParametersLayout.addWidget(self.loadFeaturesLabel, 10, 0, 1, 2)
        self.featuresFish1Label = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.featuresFish1Label.setAlignment(QtCore.Qt.AlignCenter)
        self.featuresFish1Label.setObjectName(_fromUtf8("featuresFish1Label"))
        self.step3ParametersLayout.addWidget(self.featuresFish1Label, 0, 0, 1, 1)
        self.featuresFish2Label = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.featuresFish2Label.setAlignment(QtCore.Qt.AlignCenter)
        self.featuresFish2Label.setObjectName(_fromUtf8("featuresFish2Label"))
        self.step3ParametersLayout.addWidget(self.featuresFish2Label, 0, 1, 1, 1)
        self.saveFeatures1LineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.saveFeatures1LineEdit.setObjectName(_fromUtf8("saveFeatures1LineEdit"))
        self.step3ParametersLayout.addWidget(self.saveFeatures1LineEdit, 2, 0, 1, 1)
        self.saveFeatures2LineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.saveFeatures2LineEdit.setObjectName(_fromUtf8("saveFeatures2LineEdit"))
        self.step3ParametersLayout.addWidget(self.saveFeatures2LineEdit, 2, 1, 1, 1)
        self.loadFeatures1LineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.loadFeatures1LineEdit.setObjectName(_fromUtf8("loadFeatures1LineEdit"))
        self.step3ParametersLayout.addWidget(self.loadFeatures1LineEdit, 11, 0, 1, 1)
        self.loadFeatures2LineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.loadFeatures2LineEdit.setObjectName(_fromUtf8("loadFeatures2LineEdit"))
        self.step3ParametersLayout.addWidget(self.loadFeatures2LineEdit, 11, 1, 1, 1)
        self.saveFilterLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.saveFilterLabel.setObjectName(_fromUtf8("saveFilterLabel"))
        self.step3ParametersLayout.addWidget(self.saveFilterLabel, 3, 0, 1, 1)
        self.saveFilterLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.saveFilterLineEdit.setObjectName(_fromUtf8("saveFilterLineEdit"))
        self.step3ParametersLayout.addWidget(self.saveFilterLineEdit, 4, 0, 1, 2)
        self.numberFeaturesLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.numberFeaturesLineEdit.setObjectName(_fromUtf8("numberFeaturesLineEdit"))
        self.step3ParametersLayout.addWidget(self.numberFeaturesLineEdit, 6, 0, 1, 2)
        self.extractFeaturesBut = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.extractFeaturesBut.setObjectName(_fromUtf8("extractFeaturesBut"))
        self.step3ParametersLayout.addWidget(self.extractFeaturesBut, 8, 0, 1, 2)
        self.step3Layout.addLayout(self.step3ParametersLayout)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        self.step3Layout.addItem(spacerItem4)
        self.step3Layout.setStretch(1, 4)
        self.gridLayout_2.addLayout(self.step3Layout, 2, 4, 1, 1)
        self.line_2 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_2.addWidget(self.line_2, 3, 0, 1, 5)
        self.step4Layout = QtGui.QVBoxLayout()
        self.step4Layout.setObjectName(_fromUtf8("step4Layout"))
        self.step4TitleLabel = clickQLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.step4TitleLabel.setFont(font)
        self.step4TitleLabel.setObjectName(_fromUtf8("step4TitleLabel"))
        self.step4Layout.addWidget(self.step4TitleLabel)
        self.step4ParametersLayout = QtGui.QGridLayout()
        self.step4ParametersLayout.setObjectName(_fromUtf8("step4ParametersLayout"))
        self.probabilityLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.probabilityLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.probabilityLabel.setObjectName(_fromUtf8("probabilityLabel"))
        self.step4ParametersLayout.addWidget(self.probabilityLabel, 3, 2, 1, 1)
        self.trainingLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.trainingLabel.setObjectName(_fromUtf8("trainingLabel"))
        self.step4ParametersLayout.addWidget(self.trainingLabel, 4, 0, 1, 1)
        self.testingLoadLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.testingLoadLineEdit.setObjectName(_fromUtf8("testingLoadLineEdit"))
        self.step4ParametersLayout.addWidget(self.testingLoadLineEdit, 6, 4, 1, 1)
        self.testingProbabilityLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.testingProbabilityLineEdit.setObjectName(_fromUtf8("testingProbabilityLineEdit"))
        self.step4ParametersLayout.addWidget(self.testingProbabilityLineEdit, 6, 2, 1, 1)
        self.trainingLoadLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.trainingLoadLineEdit.setObjectName(_fromUtf8("trainingLoadLineEdit"))
        self.step4ParametersLayout.addWidget(self.trainingLoadLineEdit, 4, 4, 1, 1)
        self.crossNumberSamplesLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.crossNumberSamplesLineEdit.setObjectName(_fromUtf8("crossNumberSamplesLineEdit"))
        self.step4ParametersLayout.addWidget(self.crossNumberSamplesLineEdit, 5, 1, 1, 1)
        self.trainingNumberSamplesLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.trainingNumberSamplesLineEdit.setObjectName(_fromUtf8("trainingNumberSamplesLineEdit"))
        self.step4ParametersLayout.addWidget(self.trainingNumberSamplesLineEdit, 4, 1, 1, 1)
        self.numberSamplesLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.numberSamplesLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.numberSamplesLabel.setObjectName(_fromUtf8("numberSamplesLabel"))
        self.step4ParametersLayout.addWidget(self.numberSamplesLabel, 3, 1, 1, 1)
        self.loadSlicesLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.loadSlicesLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.loadSlicesLabel.setObjectName(_fromUtf8("loadSlicesLabel"))
        self.step4ParametersLayout.addWidget(self.loadSlicesLabel, 3, 4, 1, 1)
        self.crossValidationLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.crossValidationLabel.setObjectName(_fromUtf8("crossValidationLabel"))
        self.step4ParametersLayout.addWidget(self.crossValidationLabel, 5, 0, 1, 1)
        self.testingLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.testingLabel.setObjectName(_fromUtf8("testingLabel"))
        self.step4ParametersLayout.addWidget(self.testingLabel, 6, 0, 1, 1)
        self.testingNumberSamplesLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.testingNumberSamplesLineEdit.setObjectName(_fromUtf8("testingNumberSamplesLineEdit"))
        self.step4ParametersLayout.addWidget(self.testingNumberSamplesLineEdit, 6, 1, 1, 1)
        self.crossLoadLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.crossLoadLineEdit.setObjectName(_fromUtf8("crossLoadLineEdit"))
        self.step4ParametersLayout.addWidget(self.crossLoadLineEdit, 5, 4, 1, 1)
        self.crossSaveLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.crossSaveLineEdit.setObjectName(_fromUtf8("crossSaveLineEdit"))
        self.step4ParametersLayout.addWidget(self.crossSaveLineEdit, 5, 3, 1, 1)
        self.crossProbabilityLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.crossProbabilityLineEdit.setObjectName(_fromUtf8("crossProbabilityLineEdit"))
        self.step4ParametersLayout.addWidget(self.crossProbabilityLineEdit, 5, 2, 1, 1)
        self.trainingProbabilityLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.trainingProbabilityLineEdit.setObjectName(_fromUtf8("trainingProbabilityLineEdit"))
        self.step4ParametersLayout.addWidget(self.trainingProbabilityLineEdit, 4, 2, 1, 1)
        self.sliceBut = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.sliceBut.setObjectName(_fromUtf8("sliceBut"))
        self.step4ParametersLayout.addWidget(self.sliceBut, 7, 0, 1, 5)
        self.testingSaveLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.testingSaveLineEdit.setObjectName(_fromUtf8("testingSaveLineEdit"))
        self.step4ParametersLayout.addWidget(self.testingSaveLineEdit, 6, 3, 1, 1)
        self.saveSlicesLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.saveSlicesLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.saveSlicesLabel.setObjectName(_fromUtf8("saveSlicesLabel"))
        self.step4ParametersLayout.addWidget(self.saveSlicesLabel, 3, 3, 1, 1)
        self.trainingSaveLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.trainingSaveLineEdit.setObjectName(_fromUtf8("trainingSaveLineEdit"))
        self.step4ParametersLayout.addWidget(self.trainingSaveLineEdit, 4, 3, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.step4ParametersLayout.addItem(spacerItem5, 3, 0, 1, 1)
        self.fish1Radio = QtGui.QRadioButton(self.scrollAreaWidgetContents)
        self.fish1Radio.setObjectName(_fromUtf8("fish1Radio"))
        self.step4ParametersLayout.addWidget(self.fish1Radio, 1, 0, 1, 1)
        self.fish2Radio = QtGui.QRadioButton(self.scrollAreaWidgetContents)
        self.fish2Radio.setObjectName(_fromUtf8("fish2Radio"))
        self.step4ParametersLayout.addWidget(self.fish2Radio, 1, 1, 1, 1)
        self.sliceInfoLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.sliceInfoLabel.setObjectName(_fromUtf8("sliceInfoLabel"))
        self.step4ParametersLayout.addWidget(self.sliceInfoLabel, 2, 0, 1, 5)
        self.step4Layout.addLayout(self.step4ParametersLayout)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.step4Layout.addItem(spacerItem6)
        self.gridLayout_2.addLayout(self.step4Layout, 4, 0, 1, 5)
        self.line_1 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.line_1.setFrameShape(QtGui.QFrame.HLine)
        self.line_1.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_1.setObjectName(_fromUtf8("line_1"))
        self.gridLayout_2.addWidget(self.line_1, 5, 0, 1, 1)
        self.line_3 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout_2.addWidget(self.line_3, 5, 2, 1, 3)
        self.step5Layout = QtGui.QVBoxLayout()
        self.step5Layout.setObjectName(_fromUtf8("step5Layout"))
        self.step5TitleLabel = clickQLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.step5TitleLabel.setFont(font)
        self.step5TitleLabel.setObjectName(_fromUtf8("step5TitleLabel"))
        self.step5Layout.addWidget(self.step5TitleLabel)
        self.step5ParametersLayout = QtGui.QGridLayout()
        self.step5ParametersLayout.setObjectName(_fromUtf8("step5ParametersLayout"))
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.step5ParametersLayout.addItem(spacerItem7, 1, 0, 1, 1)
        self.defaultValuesBut = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.defaultValuesBut.setObjectName(_fromUtf8("defaultValuesBut"))
        self.step5ParametersLayout.addWidget(self.defaultValuesBut, 0, 0, 1, 5)
        self.saveSVMLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.saveSVMLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.saveSVMLabel.setObjectName(_fromUtf8("saveSVMLabel"))
        self.step5ParametersLayout.addWidget(self.saveSVMLabel, 5, 0, 1, 1)
        self.valueLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.valueLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.valueLabel.setObjectName(_fromUtf8("valueLabel"))
        self.step5ParametersLayout.addWidget(self.valueLabel, 1, 4, 1, 1)
        self.trainSVMBut = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.trainSVMBut.setObjectName(_fromUtf8("trainSVMBut"))
        self.step5ParametersLayout.addWidget(self.trainSVMBut, 6, 0, 1, 5)
        self.startLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.startLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.startLabel.setObjectName(_fromUtf8("startLabel"))
        self.step5ParametersLayout.addWidget(self.startLabel, 1, 1, 1, 1)
        self.stopLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.stopLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.stopLabel.setObjectName(_fromUtf8("stopLabel"))
        self.step5ParametersLayout.addWidget(self.stopLabel, 1, 2, 1, 1)
        self.gStopLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.gStopLineEdit.setObjectName(_fromUtf8("gStopLineEdit"))
        self.step5ParametersLayout.addWidget(self.gStopLineEdit, 3, 2, 1, 1)
        self.saveSVMLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.saveSVMLineEdit.setObjectName(_fromUtf8("saveSVMLineEdit"))
        self.step5ParametersLayout.addWidget(self.saveSVMLineEdit, 5, 1, 1, 4)
        self.cStepLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.cStepLineEdit.setObjectName(_fromUtf8("cStepLineEdit"))
        self.step5ParametersLayout.addWidget(self.cStepLineEdit, 2, 3, 1, 1)
        self.cValueLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.cValueLineEdit.setObjectName(_fromUtf8("cValueLineEdit"))
        self.step5ParametersLayout.addWidget(self.cValueLineEdit, 2, 4, 1, 1)
        self.gStartLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.gStartLineEdit.setObjectName(_fromUtf8("gStartLineEdit"))
        self.step5ParametersLayout.addWidget(self.gStartLineEdit, 3, 1, 1, 1)
        self.gStepLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.gStepLineEdit.setObjectName(_fromUtf8("gStepLineEdit"))
        self.step5ParametersLayout.addWidget(self.gStepLineEdit, 3, 3, 1, 1)
        self.cLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.cLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.cLabel.setObjectName(_fromUtf8("cLabel"))
        self.step5ParametersLayout.addWidget(self.cLabel, 2, 0, 1, 1)
        self.gValueLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.gValueLineEdit.setObjectName(_fromUtf8("gValueLineEdit"))
        self.step5ParametersLayout.addWidget(self.gValueLineEdit, 3, 4, 1, 1)
        self.cStartLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.cStartLineEdit.setObjectName(_fromUtf8("cStartLineEdit"))
        self.step5ParametersLayout.addWidget(self.cStartLineEdit, 2, 1, 1, 1)
        self.gLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.gLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.gLabel.setObjectName(_fromUtf8("gLabel"))
        self.step5ParametersLayout.addWidget(self.gLabel, 3, 0, 1, 1)
        self.cStopLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.cStopLineEdit.setObjectName(_fromUtf8("cStopLineEdit"))
        self.step5ParametersLayout.addWidget(self.cStopLineEdit, 2, 2, 1, 1)
        self.stepLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.stepLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.stepLabel.setObjectName(_fromUtf8("stepLabel"))
        self.step5ParametersLayout.addWidget(self.stepLabel, 1, 3, 1, 1)
        self.optimizeSVMBut = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.optimizeSVMBut.setObjectName(_fromUtf8("optimizeSVMBut"))
        self.step5ParametersLayout.addWidget(self.optimizeSVMBut, 4, 0, 1, 5)
        self.step5Layout.addLayout(self.step5ParametersLayout)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.step5Layout.addItem(spacerItem8)
        self.logoPixMap = KPixmapRegionSelectorWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logoPixMap.sizePolicy().hasHeightForWidth())
        self.logoPixMap.setSizePolicy(sizePolicy)
        self.logoPixMap.setPixmap(QtGui.QPixmap(_fromUtf8("../../../Dropbox/LogoClaro_comLogo_w300.png")))
        self.logoPixMap.setObjectName(_fromUtf8("logoPixMap"))
        self.step5Layout.addWidget(self.logoPixMap)
        self.gridLayout_2.addLayout(self.step5Layout, 6, 0, 1, 1)
        self.line_5 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.gridLayout_2.addWidget(self.line_5, 6, 1, 1, 1)
        self.rocCurveLayout = QtGui.QGridLayout()
        self.rocCurveLayout.setObjectName(_fromUtf8("rocCurveLayout"))
        self.loadSVMLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.loadSVMLabel.setObjectName(_fromUtf8("loadSVMLabel"))
        self.rocCurveLayout.addWidget(self.loadSVMLabel, 1, 0, 1, 1)
        self.loadSVMLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.loadSVMLineEdit.setObjectName(_fromUtf8("loadSVMLineEdit"))
        self.rocCurveLayout.addWidget(self.loadSVMLineEdit, 1, 1, 1, 1)
        self.generateROCBut = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.generateROCBut.setObjectName(_fromUtf8("generateROCBut"))
        self.rocCurveLayout.addWidget(self.generateROCBut, 2, 0, 1, 2)
        self.ROCWidget = ROCWidget(self.scrollAreaWidgetContents)
        self.ROCWidget.setMinimumSize(QtCore.QSize(200, 200))
        self.ROCWidget.setObjectName(_fromUtf8("ROCWidget"))
        self.rocCurveLayout.addWidget(self.ROCWidget, 0, 0, 1, 2)
        self.gridLayout_2.addLayout(self.rocCurveLayout, 6, 2, 1, 3)
        spacerItem9 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem9, 7, 0, 1, 5)
        spacerItem10 = QtGui.QSpacerItem(529, 57, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem10, 1, 0, 1, 2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(trainingWindow)
        QtCore.QMetaObject.connectSlotsByName(trainingWindow)

    def retranslateUi(self, trainingWindow):
        trainingWindow.setWindowTitle(_translate("trainingWindow", "gymnotools - Training", None))
        self.saveParametersBut.setText(_translate("trainingWindow", "Save parameters", None))
        self.loadParametersBut.setText(_translate("trainingWindow", "Load parameters", None))
        self.step1TitleLabel.setText(_translate("trainingWindow", "1. Select parameters for spike detection v", None))
        self.thresholdAssist2But.setText(_translate("trainingWindow", "Threshold Assistant", None))
        self.spikeParametersFish1Label.setText(_translate("trainingWindow", "Fish 1", None))
        self.saturationLabel.setText(_translate("trainingWindow", "Saturation level:", None))
        self.thresholdLabel.setText(_translate("trainingWindow", "Threshold:", None))
        self.filterLabel.setText(_translate("trainingWindow", "Low-pass filter parameters:", None))
        self.thresholdLevelLabel.setText(_translate("trainingWindow", "Threshold level:", None))
        self.filterAssist2But.setText(_translate("trainingWindow", "Filter Assistant", None))
        self.spikeParametersFish2Label.setText(_translate("trainingWindow", "Fish 2", None))
        self.thresholdAssist1But.setText(_translate("trainingWindow", "Threshold Assistant", None))
        self.filterAssist1But.setText(_translate("trainingWindow", "Filter Assistant", None))
        self.cutoffLabel.setText(_translate("trainingWindow", "Cutoff frequency:", None))
        self.highSaturationLabel.setText(_translate("trainingWindow", "HIGH saturation level", None))
        self.lowSaturationLabel.setText(_translate("trainingWindow", "LOW saturation level", None))
        self.tapsLabel.setText(_translate("trainingWindow", "Number of taps:", None))
        self.loadTSLabel.setText(_translate("trainingWindow", "Load timeseries data:", None))
        self.step2TitleLabel.setText(_translate("trainingWindow", "2. Detect Spikes v", None))
        self.verifySpikes1But.setText(_translate("trainingWindow", "Verify detection", None))
        self.detectSpikes1But.setText(_translate("trainingWindow", "Detect Spikes", None))
        self.detectSpikes2But.setText(_translate("trainingWindow", "Detect Spikes", None))
        self.detectFish2Label.setText(_translate("trainingWindow", "Fish 2", None))
        self.detectFish1Label.setText(_translate("trainingWindow", "Fish 1", None))
        self.saveSpikesLabel.setText(_translate("trainingWindow", "Save detected spikes as: ", None))
        self.saveWindowLengthsLabel.setText(_translate("trainingWindow", "Save window lengths as:", None))
        self.loadSpikesLabel.setText(_translate("trainingWindow", "Load spikes file:", None))
        self.verifySpikes2But.setText(_translate("trainingWindow", "Verify detection", None))
        self.step3TitleLabel.setText(_translate("trainingWindow", "3. Rescale and extract features v", None))
        self.numberFeaturesLabel.setText(_translate("trainingWindow", "Number of features: ", None))
        self.saveFeaturesLabel.setText(_translate("trainingWindow", "Save features as:", None))
        self.loadFeaturesLabel.setText(_translate("trainingWindow", "Load features file: ", None))
        self.featuresFish1Label.setText(_translate("trainingWindow", "Fish 1", None))
        self.featuresFish2Label.setText(_translate("trainingWindow", "Fish 2", None))
        self.saveFilterLabel.setText(_translate("trainingWindow", "Save filter as:", None))
        self.extractFeaturesBut.setText(_translate("trainingWindow", "Extract features", None))
        self.step4TitleLabel.setText(_translate("trainingWindow", "4. Slice series to make training, cross validation and testing sets v", None))
        self.probabilityLabel.setText(_translate("trainingWindow", "Probability of selection", None))
        self.trainingLabel.setText(_translate("trainingWindow", "Training set: ", None))
        self.numberSamplesLabel.setText(_translate("trainingWindow", "Number of samples", None))
        self.loadSlicesLabel.setText(_translate("trainingWindow", "Load slice:", None))
        self.crossValidationLabel.setText(_translate("trainingWindow", "Cross validation set: ", None))
        self.testingLabel.setText(_translate("trainingWindow", "Testing set: ", None))
        self.sliceBut.setText(_translate("trainingWindow", "Slice", None))
        self.saveSlicesLabel.setText(_translate("trainingWindow", "Save as:", None))
        self.fish1Radio.setText(_translate("trainingWindow", "Fish 1", None))
        self.fish2Radio.setText(_translate("trainingWindow", "Fish 2", None))
        self.sliceInfoLabel.setText(_translate("trainingWindow", "Total number of windows: ", None))
        self.step5TitleLabel.setText(_translate("trainingWindow", "5. Train SVM v", None))
        self.defaultValuesBut.setText(_translate("trainingWindow", "Default values", None))
        self.saveSVMLabel.setText(_translate("trainingWindow", "Save SVM model as: ", None))
        self.valueLabel.setText(_translate("trainingWindow", "Selected value", None))
        self.trainSVMBut.setText(_translate("trainingWindow", "Train SVM", None))
        self.startLabel.setText(_translate("trainingWindow", "Start", None))
        self.stopLabel.setText(_translate("trainingWindow", "Stop", None))
        self.cLabel.setText(_translate("trainingWindow", "SVM C Parameter: ", None))
        self.gLabel.setText(_translate("trainingWindow", "SVM G Parameter: ", None))
        self.stepLabel.setText(_translate("trainingWindow", "Step", None))
        self.optimizeSVMBut.setText(_translate("trainingWindow", "Optimize Parameters", None))
        self.loadSVMLabel.setText(_translate("trainingWindow", "Load SVM model: ", None))
        self.generateROCBut.setText(_translate("trainingWindow", "Generate ROC Curve", None))

from PyKDE4.kdeui import KPixmapRegionSelectorWidget
from clickQlabel import clickQLabel
from ROCAux import ROCWidget
