# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'training_interface.ui'
#
# Created: Wed Jun  3 13:06:07 2015
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_trainingWindow(object):
    def setupUi(self, trainingWindow):
        trainingWindow.setObjectName(_fromUtf8("trainingWindow"))
        trainingWindow.setWindowModality(QtCore.Qt.WindowModal)
        trainingWindow.resize(1117, 1149)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(trainingWindow.sizePolicy().hasHeightForWidth())
        trainingWindow.setSizePolicy(sizePolicy)
        self.gridLayout = QtGui.QGridLayout(trainingWindow)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.scrollArea = QtGui.QScrollArea(trainingWindow)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1272, 1112))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_2 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.step1Layout = QtGui.QVBoxLayout()
        self.step1Layout.setObjectName(_fromUtf8("step1Layout"))
        self.step1TitleLabel = ClickQLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.step1TitleLabel.setFont(font)
        self.step1TitleLabel.setObjectName(_fromUtf8("step1TitleLabel"))
        self.step1Layout.addWidget(self.step1TitleLabel)
        self.step1ParametersLayout = QtGui.QGridLayout()
        self.step1ParametersLayout.setObjectName(_fromUtf8("step1ParametersLayout"))
        self.thresholdLevelLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.thresholdLevelLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.thresholdLevelLabel.setObjectName(_fromUtf8("thresholdLevelLabel"))
        self.step1ParametersLayout.addWidget(self.thresholdLevelLabel, 11, 0, 1, 1)
        self.filterAssist2But = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.filterAssist2But.setObjectName(_fromUtf8("filterAssist2But"))
        self.step1ParametersLayout.addWidget(self.filterAssist2But, 6, 2, 1, 1)
        self.taps2LineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.taps2LineEdit.setText(_fromUtf8(""))
        self.taps2LineEdit.setObjectName(_fromUtf8("taps2LineEdit"))
        self.step1ParametersLayout.addWidget(self.taps2LineEdit, 7, 2, 1, 1)
        self.spikeParametersFish2Label = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.spikeParametersFish2Label.setAlignment(QtCore.Qt.AlignCenter)
        self.spikeParametersFish2Label.setObjectName(_fromUtf8("spikeParametersFish2Label"))
        self.step1ParametersLayout.addWidget(self.spikeParametersFish2Label, 0, 2, 1, 1)
        self.lowSaturation2LineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lowSaturation2LineEdit.setObjectName(_fromUtf8("lowSaturation2LineEdit"))
        self.step1ParametersLayout.addWidget(self.lowSaturation2LineEdit, 3, 2, 1, 1)
        self.highSaturation2LineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.highSaturation2LineEdit.setObjectName(_fromUtf8("highSaturation2LineEdit"))
        self.step1ParametersLayout.addWidget(self.highSaturation2LineEdit, 4, 2, 1, 1)
        self.thresholdAssist1But = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.thresholdAssist1But.setObjectName(_fromUtf8("thresholdAssist1But"))
        self.step1ParametersLayout.addWidget(self.thresholdAssist1But, 10, 1, 1, 1)
        self.thresholdLevel2LineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.thresholdLevel2LineEdit.setObjectName(_fromUtf8("thresholdLevel2LineEdit"))
        self.step1ParametersLayout.addWidget(self.thresholdLevel2LineEdit, 11, 2, 1, 1)
        self.cutoffLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.cutoffLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.cutoffLabel.setObjectName(_fromUtf8("cutoffLabel"))
        self.step1ParametersLayout.addWidget(self.cutoffLabel, 8, 0, 1, 1)
        self.highSaturationLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.highSaturationLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.highSaturationLabel.setObjectName(_fromUtf8("highSaturationLabel"))
        self.step1ParametersLayout.addWidget(self.highSaturationLabel, 4, 0, 1, 1)
        self.lowSaturationLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lowSaturationLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.lowSaturationLabel.setObjectName(_fromUtf8("lowSaturationLabel"))
        self.step1ParametersLayout.addWidget(self.lowSaturationLabel, 3, 0, 1, 1)
        self.tapsLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.tapsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.tapsLabel.setObjectName(_fromUtf8("tapsLabel"))
        self.step1ParametersLayout.addWidget(self.tapsLabel, 7, 0, 1, 1)
        self.loadTSLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.loadTSLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.loadTSLabel.setObjectName(_fromUtf8("loadTSLabel"))
        self.step1ParametersLayout.addWidget(self.loadTSLabel, 1, 0, 1, 1)
        self.cutoff2LineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.cutoff2LineEdit.setText(_fromUtf8(""))
        self.cutoff2LineEdit.setObjectName(_fromUtf8("cutoff2LineEdit"))
        self.step1ParametersLayout.addWidget(self.cutoff2LineEdit, 8, 2, 1, 1)
        self.thresholdAssist2But = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.thresholdAssist2But.setObjectName(_fromUtf8("thresholdAssist2But"))
        self.step1ParametersLayout.addWidget(self.thresholdAssist2But, 10, 2, 1, 1)
        self.spikeParametersFish1Label = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.spikeParametersFish1Label.setAlignment(QtCore.Qt.AlignCenter)
        self.spikeParametersFish1Label.setObjectName(_fromUtf8("spikeParametersFish1Label"))
        self.step1ParametersLayout.addWidget(self.spikeParametersFish1Label, 0, 1, 1, 1)
        self.saturationLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setBold(True)
        font.setWeight(75)
        self.saturationLabel.setFont(font)
        self.saturationLabel.setObjectName(_fromUtf8("saturationLabel"))
        self.step1ParametersLayout.addWidget(self.saturationLabel, 2, 0, 1, 1)
        self.cutoff1LineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.cutoff1LineEdit.setText(_fromUtf8(""))
        self.cutoff1LineEdit.setObjectName(_fromUtf8("cutoff1LineEdit"))
        self.step1ParametersLayout.addWidget(self.cutoff1LineEdit, 8, 1, 1, 1)
        self.lowSaturation1LineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lowSaturation1LineEdit.setObjectName(_fromUtf8("lowSaturation1LineEdit"))
        self.step1ParametersLayout.addWidget(self.lowSaturation1LineEdit, 3, 1, 1, 1)
        self.taps1LineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.taps1LineEdit.setText(_fromUtf8(""))
        self.taps1LineEdit.setObjectName(_fromUtf8("taps1LineEdit"))
        self.step1ParametersLayout.addWidget(self.taps1LineEdit, 7, 1, 1, 1)
        self.loadTS1LineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.loadTS1LineEdit.setObjectName(_fromUtf8("loadTS1LineEdit"))
        self.step1ParametersLayout.addWidget(self.loadTS1LineEdit, 1, 1, 1, 1)
        self.thresholdLevel1LineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.thresholdLevel1LineEdit.setObjectName(_fromUtf8("thresholdLevel1LineEdit"))
        self.step1ParametersLayout.addWidget(self.thresholdLevel1LineEdit, 11, 1, 1, 1)
        self.highSaturation1LineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.highSaturation1LineEdit.setObjectName(_fromUtf8("highSaturation1LineEdit"))
        self.step1ParametersLayout.addWidget(self.highSaturation1LineEdit, 4, 1, 1, 1)
        self.thresholdLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setBold(True)
        font.setWeight(75)
        self.thresholdLabel.setFont(font)
        self.thresholdLabel.setObjectName(_fromUtf8("thresholdLabel"))
        self.step1ParametersLayout.addWidget(self.thresholdLabel, 9, 0, 1, 1)
        self.filterLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setBold(True)
        font.setWeight(75)
        self.filterLabel.setFont(font)
        self.filterLabel.setObjectName(_fromUtf8("filterLabel"))
        self.step1ParametersLayout.addWidget(self.filterLabel, 5, 0, 1, 1)
        self.loadTS2LineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.loadTS2LineEdit.setObjectName(_fromUtf8("loadTS2LineEdit"))
        self.step1ParametersLayout.addWidget(self.loadTS2LineEdit, 1, 2, 1, 1)
        self.filterAssist1But = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.filterAssist1But.setObjectName(_fromUtf8("filterAssist1But"))
        self.step1ParametersLayout.addWidget(self.filterAssist1But, 6, 1, 1, 1)
        self.step1Layout.addLayout(self.step1ParametersLayout)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.step1Layout.addItem(spacerItem)
        self.step1Layout.setStretch(1, 4)
        self.gridLayout_2.addLayout(self.step1Layout, 1, 0, 1, 1)
        self.saveLoadParametersLayout = QtGui.QHBoxLayout()
        self.saveLoadParametersLayout.setObjectName(_fromUtf8("saveLoadParametersLayout"))
        self.saveParametersBut = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.saveParametersBut.setObjectName(_fromUtf8("saveParametersBut"))
        self.saveLoadParametersLayout.addWidget(self.saveParametersBut)
        self.loadParametersBut = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.loadParametersBut.setObjectName(_fromUtf8("loadParametersBut"))
        self.saveLoadParametersLayout.addWidget(self.loadParametersBut)
        self.gridLayout_2.addLayout(self.saveLoadParametersLayout, 0, 0, 1, 5)
        self.line_0 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.line_0.setFrameShape(QtGui.QFrame.VLine)
        self.line_0.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_0.setObjectName(_fromUtf8("line_0"))
        self.gridLayout_2.addWidget(self.line_0, 1, 1, 1, 1)
        self.step2Layout = QtGui.QVBoxLayout()
        self.step2Layout.setObjectName(_fromUtf8("step2Layout"))
        self.step2TitleLabel = ClickQLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.step2TitleLabel.setFont(font)
        self.step2TitleLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.step2TitleLabel.setObjectName(_fromUtf8("step2TitleLabel"))
        self.step2Layout.addWidget(self.step2TitleLabel)
        self.step2ParametersLayout = QtGui.QGridLayout()
        self.step2ParametersLayout.setHorizontalSpacing(6)
        self.step2ParametersLayout.setVerticalSpacing(0)
        self.step2ParametersLayout.setObjectName(_fromUtf8("step2ParametersLayout"))
        self.saveSpikesLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.saveSpikesLabel.setObjectName(_fromUtf8("saveSpikesLabel"))
        self.step2ParametersLayout.addWidget(self.saveSpikesLabel, 1, 0, 1, 3)
        self.saveWindowLengths1LineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.saveWindowLengths1LineEdit.setObjectName(_fromUtf8("saveWindowLengths1LineEdit"))
        self.step2ParametersLayout.addWidget(self.saveWindowLengths1LineEdit, 4, 0, 1, 2)
        self.saveWindowLengthsLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.saveWindowLengthsLabel.setObjectName(_fromUtf8("saveWindowLengthsLabel"))
        self.step2ParametersLayout.addWidget(self.saveWindowLengthsLabel, 3, 0, 1, 3)
        self.verifySpikes2But = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.verifySpikes2But.setObjectName(_fromUtf8("verifySpikes2But"))
        self.step2ParametersLayout.addWidget(self.verifySpikes2But, 11, 2, 1, 1)
        self.loadSpikesLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.loadSpikesLabel.setObjectName(_fromUtf8("loadSpikesLabel"))
        self.step2ParametersLayout.addWidget(self.loadSpikesLabel, 9, 0, 1, 3)
        self.loadSpikes2LineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.loadSpikes2LineEdit.setObjectName(_fromUtf8("loadSpikes2LineEdit"))
        self.step2ParametersLayout.addWidget(self.loadSpikes2LineEdit, 10, 2, 1, 1)
        self.onlyAboveLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.onlyAboveLabel.setObjectName(_fromUtf8("onlyAboveLabel"))
        self.step2ParametersLayout.addWidget(self.onlyAboveLabel, 5, 0, 1, 3)
        self.detectFish2Label = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.detectFish2Label.setAlignment(QtCore.Qt.AlignCenter)
        self.detectFish2Label.setObjectName(_fromUtf8("detectFish2Label"))
        self.step2ParametersLayout.addWidget(self.detectFish2Label, 0, 2, 1, 1)
        self.saveWindowLengths2LineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.saveWindowLengths2LineEdit.setObjectName(_fromUtf8("saveWindowLengths2LineEdit"))
        self.step2ParametersLayout.addWidget(self.saveWindowLengths2LineEdit, 4, 2, 1, 1)
        self.verifySpikes1But = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.verifySpikes1But.setObjectName(_fromUtf8("verifySpikes1But"))
        self.step2ParametersLayout.addWidget(self.verifySpikes1But, 11, 0, 1, 2)
        self.saveSpikes2LineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.saveSpikes2LineEdit.setObjectName(_fromUtf8("saveSpikes2LineEdit"))
        self.step2ParametersLayout.addWidget(self.saveSpikes2LineEdit, 2, 2, 1, 1)
        self.saveSpikes1LineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.saveSpikes1LineEdit.setObjectName(_fromUtf8("saveSpikes1LineEdit"))
        self.step2ParametersLayout.addWidget(self.saveSpikes1LineEdit, 2, 0, 1, 2)
        self.detectSpikes1But = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.detectSpikes1But.setObjectName(_fromUtf8("detectSpikes1But"))
        self.step2ParametersLayout.addWidget(self.detectSpikes1But, 7, 0, 1, 2)
        self.detectFish1Label = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.detectFish1Label.setAlignment(QtCore.Qt.AlignCenter)
        self.detectFish1Label.setObjectName(_fromUtf8("detectFish1Label"))
        self.step2ParametersLayout.addWidget(self.detectFish1Label, 0, 0, 1, 2)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.step2ParametersLayout.addItem(spacerItem1, 8, 0, 1, 3)
        self.detectSpikes2But = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.detectSpikes2But.setObjectName(_fromUtf8("detectSpikes2But"))
        self.step2ParametersLayout.addWidget(self.detectSpikes2But, 7, 2, 1, 1)
        self.loadSpikes1LineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.loadSpikes1LineEdit.setObjectName(_fromUtf8("loadSpikes1LineEdit"))
        self.step2ParametersLayout.addWidget(self.loadSpikes1LineEdit, 10, 0, 1, 2)
        self.onlyAbove2LineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.onlyAbove2LineEdit.setObjectName(_fromUtf8("onlyAbove2LineEdit"))
        self.step2ParametersLayout.addWidget(self.onlyAbove2LineEdit, 6, 2, 1, 1)
        self.onlyAbove1LineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.onlyAbove1LineEdit.setObjectName(_fromUtf8("onlyAbove1LineEdit"))
        self.step2ParametersLayout.addWidget(self.onlyAbove1LineEdit, 6, 0, 1, 2)
        self.step2ParametersLayout.setColumnStretch(0, 4)
        self.step2ParametersLayout.setColumnStretch(2, 4)
        self.step2Layout.addLayout(self.step2ParametersLayout)
        self.step2Layout.setStretch(1, 4)
        self.gridLayout_2.addLayout(self.step2Layout, 1, 2, 1, 1)
        self.line_4 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout_2.addWidget(self.line_4, 1, 3, 1, 1)
        self.step3Layout = QtGui.QVBoxLayout()
        self.step3Layout.setObjectName(_fromUtf8("step3Layout"))
        self.step3TitleLabel = ClickQLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.step3TitleLabel.setFont(font)
        self.step3TitleLabel.setObjectName(_fromUtf8("step3TitleLabel"))
        self.step3Layout.addWidget(self.step3TitleLabel)
        self.step3ParametersLayout = QtGui.QGridLayout()
        self.step3ParametersLayout.setObjectName(_fromUtf8("step3ParametersLayout"))
        self.saveRescaleLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.saveRescaleLabel.setObjectName(_fromUtf8("saveRescaleLabel"))
        self.step3ParametersLayout.addWidget(self.saveRescaleLabel, 5, 0, 1, 1)
        self.numberFeaturesLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.numberFeaturesLabel.setObjectName(_fromUtf8("numberFeaturesLabel"))
        self.step3ParametersLayout.addWidget(self.numberFeaturesLabel, 7, 0, 1, 2)
        self.saveFeaturesLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.saveFeaturesLabel.setObjectName(_fromUtf8("saveFeaturesLabel"))
        self.step3ParametersLayout.addWidget(self.saveFeaturesLabel, 1, 0, 1, 2)
        self.loadFeaturesLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.loadFeaturesLabel.setObjectName(_fromUtf8("loadFeaturesLabel"))
        self.step3ParametersLayout.addWidget(self.loadFeaturesLabel, 12, 0, 1, 2)
        self.featuresFish1Label = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.featuresFish1Label.setAlignment(QtCore.Qt.AlignCenter)
        self.featuresFish1Label.setObjectName(_fromUtf8("featuresFish1Label"))
        self.step3ParametersLayout.addWidget(self.featuresFish1Label, 0, 0, 1, 1)
        self.featuresFish2Label = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.featuresFish2Label.setAlignment(QtCore.Qt.AlignCenter)
        self.featuresFish2Label.setObjectName(_fromUtf8("featuresFish2Label"))
        self.step3ParametersLayout.addWidget(self.featuresFish2Label, 0, 1, 1, 1)
        self.saveFeatures1LineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.saveFeatures1LineEdit.setObjectName(_fromUtf8("saveFeatures1LineEdit"))
        self.step3ParametersLayout.addWidget(self.saveFeatures1LineEdit, 2, 0, 1, 1)
        self.saveFeatures2LineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.saveFeatures2LineEdit.setObjectName(_fromUtf8("saveFeatures2LineEdit"))
        self.step3ParametersLayout.addWidget(self.saveFeatures2LineEdit, 2, 1, 1, 1)
        self.loadFeatures1LineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.loadFeatures1LineEdit.setObjectName(_fromUtf8("loadFeatures1LineEdit"))
        self.step3ParametersLayout.addWidget(self.loadFeatures1LineEdit, 13, 0, 1, 1)
        self.loadFeatures2LineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.loadFeatures2LineEdit.setObjectName(_fromUtf8("loadFeatures2LineEdit"))
        self.step3ParametersLayout.addWidget(self.loadFeatures2LineEdit, 13, 1, 1, 1)
        self.saveFilterLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.saveFilterLabel.setObjectName(_fromUtf8("saveFilterLabel"))
        self.step3ParametersLayout.addWidget(self.saveFilterLabel, 3, 0, 1, 1)
        self.saveFilterLineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.saveFilterLineEdit.setObjectName(_fromUtf8("saveFilterLineEdit"))
        self.step3ParametersLayout.addWidget(self.saveFilterLineEdit, 4, 0, 1, 2)
        self.numberFeaturesLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.numberFeaturesLineEdit.setObjectName(_fromUtf8("numberFeaturesLineEdit"))
        self.step3ParametersLayout.addWidget(self.numberFeaturesLineEdit, 8, 0, 1, 2)
        self.extractFeaturesBut = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.extractFeaturesBut.setObjectName(_fromUtf8("extractFeaturesBut"))
        self.step3ParametersLayout.addWidget(self.extractFeaturesBut, 10, 0, 1, 2)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.step3ParametersLayout.addItem(spacerItem2, 11, 0, 1, 2)
        self.saveRescaleLineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.saveRescaleLineEdit.setObjectName(_fromUtf8("saveRescaleLineEdit"))
        self.step3ParametersLayout.addWidget(self.saveRescaleLineEdit, 6, 0, 1, 2)
        self.step3Layout.addLayout(self.step3ParametersLayout)
        self.step3Layout.setStretch(1, 4)
        self.gridLayout_2.addLayout(self.step3Layout, 1, 4, 1, 1)
        self.line_2 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_2.addWidget(self.line_2, 2, 0, 1, 5)
        self.step4Layout = QtGui.QVBoxLayout()
        self.step4Layout.setObjectName(_fromUtf8("step4Layout"))
        self.step4TitleLabel = ClickQLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.step4TitleLabel.setFont(font)
        self.step4TitleLabel.setObjectName(_fromUtf8("step4TitleLabel"))
        self.step4Layout.addWidget(self.step4TitleLabel)
        self.tabWidget = QtGui.QTabWidget(self.scrollAreaWidgetContents)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabFish1 = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabFish1.sizePolicy().hasHeightForWidth())
        self.tabFish1.setSizePolicy(sizePolicy)
        self.tabFish1.setObjectName(_fromUtf8("tabFish1"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tabFish1)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.sliceInfoFish1Label = QtGui.QLabel(self.tabFish1)
        self.sliceInfoFish1Label.setText(_fromUtf8(""))
        self.sliceInfoFish1Label.setObjectName(_fromUtf8("sliceInfoFish1Label"))
        self.gridLayout_3.addWidget(self.sliceInfoFish1Label, 0, 0, 1, 1)
        self.numberSamplesFish1Label = QtGui.QLabel(self.tabFish1)
        self.numberSamplesFish1Label.setAlignment(QtCore.Qt.AlignCenter)
        self.numberSamplesFish1Label.setObjectName(_fromUtf8("numberSamplesFish1Label"))
        self.gridLayout_3.addWidget(self.numberSamplesFish1Label, 1, 1, 1, 1)
        self.probabilityFish1Label = QtGui.QLabel(self.tabFish1)
        self.probabilityFish1Label.setAlignment(QtCore.Qt.AlignCenter)
        self.probabilityFish1Label.setObjectName(_fromUtf8("probabilityFish1Label"))
        self.gridLayout_3.addWidget(self.probabilityFish1Label, 1, 2, 1, 1)
        self.saveSlicesFish1Label = QtGui.QLabel(self.tabFish1)
        self.saveSlicesFish1Label.setAlignment(QtCore.Qt.AlignCenter)
        self.saveSlicesFish1Label.setObjectName(_fromUtf8("saveSlicesFish1Label"))
        self.gridLayout_3.addWidget(self.saveSlicesFish1Label, 1, 3, 1, 1)
        self.loadSlicesFish1Label = QtGui.QLabel(self.tabFish1)
        self.loadSlicesFish1Label.setAlignment(QtCore.Qt.AlignCenter)
        self.loadSlicesFish1Label.setObjectName(_fromUtf8("loadSlicesFish1Label"))
        self.gridLayout_3.addWidget(self.loadSlicesFish1Label, 1, 4, 1, 1)
        self.trainingFish1Label = QtGui.QLabel(self.tabFish1)
        self.trainingFish1Label.setObjectName(_fromUtf8("trainingFish1Label"))
        self.gridLayout_3.addWidget(self.trainingFish1Label, 2, 0, 1, 1)
        self.trainingNumberSamplesFish1LineEdit = QtGui.QLineEdit(self.tabFish1)
        self.trainingNumberSamplesFish1LineEdit.setObjectName(_fromUtf8("trainingNumberSamplesFish1LineEdit"))
        self.gridLayout_3.addWidget(self.trainingNumberSamplesFish1LineEdit, 2, 1, 1, 1)
        self.trainingProbabilityFish1LineEdit = QtGui.QLineEdit(self.tabFish1)
        self.trainingProbabilityFish1LineEdit.setObjectName(_fromUtf8("trainingProbabilityFish1LineEdit"))
        self.gridLayout_3.addWidget(self.trainingProbabilityFish1LineEdit, 2, 2, 1, 1)
        self.trainingSaveFish1LineEdit = ClickQLineEdit(self.tabFish1)
        self.trainingSaveFish1LineEdit.setObjectName(_fromUtf8("trainingSaveFish1LineEdit"))
        self.gridLayout_3.addWidget(self.trainingSaveFish1LineEdit, 2, 3, 1, 1)
        self.trainingLoadFish1LineEdit = ClickQLineEdit(self.tabFish1)
        self.trainingLoadFish1LineEdit.setObjectName(_fromUtf8("trainingLoadFish1LineEdit"))
        self.gridLayout_3.addWidget(self.trainingLoadFish1LineEdit, 2, 4, 1, 1)
        self.crossValidationFish1Label = QtGui.QLabel(self.tabFish1)
        self.crossValidationFish1Label.setObjectName(_fromUtf8("crossValidationFish1Label"))
        self.gridLayout_3.addWidget(self.crossValidationFish1Label, 3, 0, 1, 1)
        self.crossNumberSamplesFish1LineEdit = QtGui.QLineEdit(self.tabFish1)
        self.crossNumberSamplesFish1LineEdit.setObjectName(_fromUtf8("crossNumberSamplesFish1LineEdit"))
        self.gridLayout_3.addWidget(self.crossNumberSamplesFish1LineEdit, 3, 1, 1, 1)
        self.crossProbabilityFish1LineEdit = QtGui.QLineEdit(self.tabFish1)
        self.crossProbabilityFish1LineEdit.setObjectName(_fromUtf8("crossProbabilityFish1LineEdit"))
        self.gridLayout_3.addWidget(self.crossProbabilityFish1LineEdit, 3, 2, 1, 1)
        self.crossSaveFish1LineEdit = ClickQLineEdit(self.tabFish1)
        self.crossSaveFish1LineEdit.setObjectName(_fromUtf8("crossSaveFish1LineEdit"))
        self.gridLayout_3.addWidget(self.crossSaveFish1LineEdit, 3, 3, 1, 1)
        self.crossLoadFish1LineEdit = ClickQLineEdit(self.tabFish1)
        self.crossLoadFish1LineEdit.setObjectName(_fromUtf8("crossLoadFish1LineEdit"))
        self.gridLayout_3.addWidget(self.crossLoadFish1LineEdit, 3, 4, 1, 1)
        self.testingFish1Label = QtGui.QLabel(self.tabFish1)
        self.testingFish1Label.setObjectName(_fromUtf8("testingFish1Label"))
        self.gridLayout_3.addWidget(self.testingFish1Label, 4, 0, 1, 1)
        self.testingNumberSamplesFish1LineEdit = QtGui.QLineEdit(self.tabFish1)
        self.testingNumberSamplesFish1LineEdit.setObjectName(_fromUtf8("testingNumberSamplesFish1LineEdit"))
        self.gridLayout_3.addWidget(self.testingNumberSamplesFish1LineEdit, 4, 1, 1, 1)
        self.testingProbabilityFish1LineEdit = QtGui.QLineEdit(self.tabFish1)
        self.testingProbabilityFish1LineEdit.setObjectName(_fromUtf8("testingProbabilityFish1LineEdit"))
        self.gridLayout_3.addWidget(self.testingProbabilityFish1LineEdit, 4, 2, 1, 1)
        self.testingSaveFish1LineEdit = ClickQLineEdit(self.tabFish1)
        self.testingSaveFish1LineEdit.setObjectName(_fromUtf8("testingSaveFish1LineEdit"))
        self.gridLayout_3.addWidget(self.testingSaveFish1LineEdit, 4, 3, 1, 1)
        self.testingLoadFish1LineEdit = ClickQLineEdit(self.tabFish1)
        self.testingLoadFish1LineEdit.setObjectName(_fromUtf8("testingLoadFish1LineEdit"))
        self.gridLayout_3.addWidget(self.testingLoadFish1LineEdit, 4, 4, 1, 1)
        self.sliceFish1But = QtGui.QPushButton(self.tabFish1)
        self.sliceFish1But.setObjectName(_fromUtf8("sliceFish1But"))
        self.gridLayout_3.addWidget(self.sliceFish1But, 5, 0, 1, 5)
        spacerItem3 = QtGui.QSpacerItem(204, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tabFish1, _fromUtf8(""))
        self.tabFish2 = QtGui.QWidget()
        self.tabFish2.setObjectName(_fromUtf8("tabFish2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tabFish2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.sliceInfoFish2Label = QtGui.QLabel(self.tabFish2)
        self.sliceInfoFish2Label.setText(_fromUtf8(""))
        self.sliceInfoFish2Label.setObjectName(_fromUtf8("sliceInfoFish2Label"))
        self.gridLayout_4.addWidget(self.sliceInfoFish2Label, 0, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(204, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem4, 1, 0, 1, 1)
        self.numberSamplesFish2Label = QtGui.QLabel(self.tabFish2)
        self.numberSamplesFish2Label.setAlignment(QtCore.Qt.AlignCenter)
        self.numberSamplesFish2Label.setObjectName(_fromUtf8("numberSamplesFish2Label"))
        self.gridLayout_4.addWidget(self.numberSamplesFish2Label, 1, 1, 1, 1)
        self.probabilityFish2Label = QtGui.QLabel(self.tabFish2)
        self.probabilityFish2Label.setAlignment(QtCore.Qt.AlignCenter)
        self.probabilityFish2Label.setObjectName(_fromUtf8("probabilityFish2Label"))
        self.gridLayout_4.addWidget(self.probabilityFish2Label, 1, 2, 1, 1)
        self.saveSlicesFish2Label = QtGui.QLabel(self.tabFish2)
        self.saveSlicesFish2Label.setAlignment(QtCore.Qt.AlignCenter)
        self.saveSlicesFish2Label.setObjectName(_fromUtf8("saveSlicesFish2Label"))
        self.gridLayout_4.addWidget(self.saveSlicesFish2Label, 1, 3, 1, 1)
        self.loadSlicesFish2Label = QtGui.QLabel(self.tabFish2)
        self.loadSlicesFish2Label.setAlignment(QtCore.Qt.AlignCenter)
        self.loadSlicesFish2Label.setObjectName(_fromUtf8("loadSlicesFish2Label"))
        self.gridLayout_4.addWidget(self.loadSlicesFish2Label, 1, 4, 1, 1)
        self.trainingFish2Label = QtGui.QLabel(self.tabFish2)
        self.trainingFish2Label.setObjectName(_fromUtf8("trainingFish2Label"))
        self.gridLayout_4.addWidget(self.trainingFish2Label, 2, 0, 1, 1)
        self.trainingNumberSamplesFish2LineEdit = QtGui.QLineEdit(self.tabFish2)
        self.trainingNumberSamplesFish2LineEdit.setObjectName(_fromUtf8("trainingNumberSamplesFish2LineEdit"))
        self.gridLayout_4.addWidget(self.trainingNumberSamplesFish2LineEdit, 2, 1, 1, 1)
        self.trainingProbabilityFish2LineEdit = QtGui.QLineEdit(self.tabFish2)
        self.trainingProbabilityFish2LineEdit.setObjectName(_fromUtf8("trainingProbabilityFish2LineEdit"))
        self.gridLayout_4.addWidget(self.trainingProbabilityFish2LineEdit, 2, 2, 1, 1)
        self.trainingSaveFish2LineEdit = ClickQLineEdit(self.tabFish2)
        self.trainingSaveFish2LineEdit.setObjectName(_fromUtf8("trainingSaveFish2LineEdit"))
        self.gridLayout_4.addWidget(self.trainingSaveFish2LineEdit, 2, 3, 1, 1)
        self.trainingLoadFish2LineEdit = ClickQLineEdit(self.tabFish2)
        self.trainingLoadFish2LineEdit.setObjectName(_fromUtf8("trainingLoadFish2LineEdit"))
        self.gridLayout_4.addWidget(self.trainingLoadFish2LineEdit, 2, 4, 1, 1)
        self.crossValidationFish2Label = QtGui.QLabel(self.tabFish2)
        self.crossValidationFish2Label.setObjectName(_fromUtf8("crossValidationFish2Label"))
        self.gridLayout_4.addWidget(self.crossValidationFish2Label, 3, 0, 1, 1)
        self.crossNumberSamplesFish2LineEdit = QtGui.QLineEdit(self.tabFish2)
        self.crossNumberSamplesFish2LineEdit.setObjectName(_fromUtf8("crossNumberSamplesFish2LineEdit"))
        self.gridLayout_4.addWidget(self.crossNumberSamplesFish2LineEdit, 3, 1, 1, 1)
        self.crossProbabilityFish2LineEdit = QtGui.QLineEdit(self.tabFish2)
        self.crossProbabilityFish2LineEdit.setObjectName(_fromUtf8("crossProbabilityFish2LineEdit"))
        self.gridLayout_4.addWidget(self.crossProbabilityFish2LineEdit, 3, 2, 1, 1)
        self.crossSaveFish2LineEdit = ClickQLineEdit(self.tabFish2)
        self.crossSaveFish2LineEdit.setObjectName(_fromUtf8("crossSaveFish2LineEdit"))
        self.gridLayout_4.addWidget(self.crossSaveFish2LineEdit, 3, 3, 1, 1)
        self.crossLoadFish2LineEdit = ClickQLineEdit(self.tabFish2)
        self.crossLoadFish2LineEdit.setObjectName(_fromUtf8("crossLoadFish2LineEdit"))
        self.gridLayout_4.addWidget(self.crossLoadFish2LineEdit, 3, 4, 1, 1)
        self.testingFish2Label = QtGui.QLabel(self.tabFish2)
        self.testingFish2Label.setObjectName(_fromUtf8("testingFish2Label"))
        self.gridLayout_4.addWidget(self.testingFish2Label, 4, 0, 1, 1)
        self.testingNumberSamplesFish2LineEdit = QtGui.QLineEdit(self.tabFish2)
        self.testingNumberSamplesFish2LineEdit.setObjectName(_fromUtf8("testingNumberSamplesFish2LineEdit"))
        self.gridLayout_4.addWidget(self.testingNumberSamplesFish2LineEdit, 4, 1, 1, 1)
        self.testingProbabilityFish2LineEdit = QtGui.QLineEdit(self.tabFish2)
        self.testingProbabilityFish2LineEdit.setObjectName(_fromUtf8("testingProbabilityFish2LineEdit"))
        self.gridLayout_4.addWidget(self.testingProbabilityFish2LineEdit, 4, 2, 1, 1)
        self.testingSaveFish2LineEdit = ClickQLineEdit(self.tabFish2)
        self.testingSaveFish2LineEdit.setObjectName(_fromUtf8("testingSaveFish2LineEdit"))
        self.gridLayout_4.addWidget(self.testingSaveFish2LineEdit, 4, 3, 1, 1)
        self.testingLoadFish2LineEdit = ClickQLineEdit(self.tabFish2)
        self.testingLoadFish2LineEdit.setObjectName(_fromUtf8("testingLoadFish2LineEdit"))
        self.gridLayout_4.addWidget(self.testingLoadFish2LineEdit, 4, 4, 1, 1)
        self.sliceFish2But = QtGui.QPushButton(self.tabFish2)
        self.sliceFish2But.setObjectName(_fromUtf8("sliceFish2But"))
        self.gridLayout_4.addWidget(self.sliceFish2But, 5, 0, 1, 5)
        self.tabWidget.addTab(self.tabFish2, _fromUtf8(""))
        self.step4Layout.addWidget(self.tabWidget)
        self.gridLayout_2.addLayout(self.step4Layout, 3, 0, 1, 5)
        self.line_1 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.line_1.setFrameShape(QtGui.QFrame.HLine)
        self.line_1.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_1.setObjectName(_fromUtf8("line_1"))
        self.gridLayout_2.addWidget(self.line_1, 4, 0, 1, 1)
        self.line_3 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout_2.addWidget(self.line_3, 4, 2, 1, 3)
        self.step5Layout = QtGui.QVBoxLayout()
        self.step5Layout.setObjectName(_fromUtf8("step5Layout"))
        self.step5TitleLabel = ClickQLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.step5TitleLabel.setFont(font)
        self.step5TitleLabel.setObjectName(_fromUtf8("step5TitleLabel"))
        self.step5Layout.addWidget(self.step5TitleLabel)
        self.step5ParametersLayout = QtGui.QGridLayout()
        self.step5ParametersLayout.setObjectName(_fromUtf8("step5ParametersLayout"))
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.step5ParametersLayout.addItem(spacerItem5, 1, 0, 1, 1)
        self.defaultSVMValuesBut = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.defaultSVMValuesBut.setObjectName(_fromUtf8("defaultSVMValuesBut"))
        self.step5ParametersLayout.addWidget(self.defaultSVMValuesBut, 0, 0, 1, 5)
        self.saveSVMLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.saveSVMLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.saveSVMLabel.setObjectName(_fromUtf8("saveSVMLabel"))
        self.step5ParametersLayout.addWidget(self.saveSVMLabel, 5, 0, 1, 1)
        self.valueLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.valueLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.valueLabel.setObjectName(_fromUtf8("valueLabel"))
        self.step5ParametersLayout.addWidget(self.valueLabel, 1, 4, 1, 1)
        self.trainSVMBut = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.trainSVMBut.setObjectName(_fromUtf8("trainSVMBut"))
        self.step5ParametersLayout.addWidget(self.trainSVMBut, 6, 0, 1, 5)
        self.startLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.startLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.startLabel.setObjectName(_fromUtf8("startLabel"))
        self.step5ParametersLayout.addWidget(self.startLabel, 1, 1, 1, 1)
        self.stopLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.stopLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.stopLabel.setObjectName(_fromUtf8("stopLabel"))
        self.step5ParametersLayout.addWidget(self.stopLabel, 1, 2, 1, 1)
        self.gStopLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.gStopLineEdit.setObjectName(_fromUtf8("gStopLineEdit"))
        self.step5ParametersLayout.addWidget(self.gStopLineEdit, 3, 2, 1, 1)
        self.saveSVMLineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.saveSVMLineEdit.setObjectName(_fromUtf8("saveSVMLineEdit"))
        self.step5ParametersLayout.addWidget(self.saveSVMLineEdit, 5, 1, 1, 4)
        self.cStepLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.cStepLineEdit.setObjectName(_fromUtf8("cStepLineEdit"))
        self.step5ParametersLayout.addWidget(self.cStepLineEdit, 2, 3, 1, 1)
        self.cValueLineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.cValueLineEdit.setObjectName(_fromUtf8("cValueLineEdit"))
        self.step5ParametersLayout.addWidget(self.cValueLineEdit, 2, 4, 1, 1)
        self.gStartLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.gStartLineEdit.setObjectName(_fromUtf8("gStartLineEdit"))
        self.step5ParametersLayout.addWidget(self.gStartLineEdit, 3, 1, 1, 1)
        self.gStepLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.gStepLineEdit.setObjectName(_fromUtf8("gStepLineEdit"))
        self.step5ParametersLayout.addWidget(self.gStepLineEdit, 3, 3, 1, 1)
        self.cLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.cLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.cLabel.setObjectName(_fromUtf8("cLabel"))
        self.step5ParametersLayout.addWidget(self.cLabel, 2, 0, 1, 1)
        self.gValueLineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.gValueLineEdit.setObjectName(_fromUtf8("gValueLineEdit"))
        self.step5ParametersLayout.addWidget(self.gValueLineEdit, 3, 4, 1, 1)
        self.cStartLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.cStartLineEdit.setObjectName(_fromUtf8("cStartLineEdit"))
        self.step5ParametersLayout.addWidget(self.cStartLineEdit, 2, 1, 1, 1)
        self.gLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.gLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.gLabel.setObjectName(_fromUtf8("gLabel"))
        self.step5ParametersLayout.addWidget(self.gLabel, 3, 0, 1, 1)
        self.cStopLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.cStopLineEdit.setObjectName(_fromUtf8("cStopLineEdit"))
        self.step5ParametersLayout.addWidget(self.cStopLineEdit, 2, 2, 1, 1)
        self.stepLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.stepLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.stepLabel.setObjectName(_fromUtf8("stepLabel"))
        self.step5ParametersLayout.addWidget(self.stepLabel, 1, 3, 1, 1)
        self.optimizeSVMBut = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.optimizeSVMBut.setObjectName(_fromUtf8("optimizeSVMBut"))
        self.step5ParametersLayout.addWidget(self.optimizeSVMBut, 4, 0, 1, 5)
        self.step5Layout.addLayout(self.step5ParametersLayout)
        self.logoPixMap = KPixmapRegionSelectorWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logoPixMap.sizePolicy().hasHeightForWidth())
        self.logoPixMap.setSizePolicy(sizePolicy)
        self.logoPixMap.setPixmap(QtGui.QPixmap(_fromUtf8("../../../Dropbox/LogoClaro_comLogo_w580.png")))
        self.logoPixMap.setObjectName(_fromUtf8("logoPixMap"))
        self.step5Layout.addWidget(self.logoPixMap)
        self.gridLayout_2.addLayout(self.step5Layout, 5, 0, 1, 1)
        self.line_5 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.gridLayout_2.addWidget(self.line_5, 5, 1, 1, 1)
        self.rocCurveLayout = QtGui.QGridLayout()
        self.rocCurveLayout.setObjectName(_fromUtf8("rocCurveLayout"))
        self.loadSVMLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.loadSVMLabel.setObjectName(_fromUtf8("loadSVMLabel"))
        self.rocCurveLayout.addWidget(self.loadSVMLabel, 1, 0, 1, 1)
        self.loadSVMLineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.loadSVMLineEdit.setObjectName(_fromUtf8("loadSVMLineEdit"))
        self.rocCurveLayout.addWidget(self.loadSVMLineEdit, 1, 1, 1, 1)
        self.generateROCBut = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.generateROCBut.setObjectName(_fromUtf8("generateROCBut"))
        self.rocCurveLayout.addWidget(self.generateROCBut, 2, 0, 1, 2)
        self.ROCWidget = ROCWidget(self.scrollAreaWidgetContents)
        self.ROCWidget.setMinimumSize(QtCore.QSize(200, 200))
        self.ROCWidget.setObjectName(_fromUtf8("ROCWidget"))
        self.rocCurveLayout.addWidget(self.ROCWidget, 0, 0, 1, 2)
        self.gridLayout_2.addLayout(self.rocCurveLayout, 5, 2, 1, 3)
        spacerItem6 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem6, 6, 0, 1, 5)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(trainingWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(trainingWindow)
        trainingWindow.setTabOrder(self.scrollArea, self.saveParametersBut)
        trainingWindow.setTabOrder(self.saveParametersBut, self.loadParametersBut)
        trainingWindow.setTabOrder(self.loadParametersBut, self.loadTS1LineEdit)
        trainingWindow.setTabOrder(self.loadTS1LineEdit, self.lowSaturation1LineEdit)
        trainingWindow.setTabOrder(self.lowSaturation1LineEdit, self.highSaturation1LineEdit)
        trainingWindow.setTabOrder(self.highSaturation1LineEdit, self.filterAssist1But)
        trainingWindow.setTabOrder(self.filterAssist1But, self.taps1LineEdit)
        trainingWindow.setTabOrder(self.taps1LineEdit, self.cutoff1LineEdit)
        trainingWindow.setTabOrder(self.cutoff1LineEdit, self.thresholdAssist1But)
        trainingWindow.setTabOrder(self.thresholdAssist1But, self.thresholdLevel1LineEdit)
        trainingWindow.setTabOrder(self.thresholdLevel1LineEdit, self.loadTS2LineEdit)
        trainingWindow.setTabOrder(self.loadTS2LineEdit, self.lowSaturation2LineEdit)
        trainingWindow.setTabOrder(self.lowSaturation2LineEdit, self.highSaturation2LineEdit)
        trainingWindow.setTabOrder(self.highSaturation2LineEdit, self.filterAssist2But)
        trainingWindow.setTabOrder(self.filterAssist2But, self.taps2LineEdit)
        trainingWindow.setTabOrder(self.taps2LineEdit, self.cutoff2LineEdit)
        trainingWindow.setTabOrder(self.cutoff2LineEdit, self.thresholdAssist2But)
        trainingWindow.setTabOrder(self.thresholdAssist2But, self.thresholdLevel2LineEdit)
        trainingWindow.setTabOrder(self.thresholdLevel2LineEdit, self.saveSpikes1LineEdit)
        trainingWindow.setTabOrder(self.saveSpikes1LineEdit, self.saveWindowLengths1LineEdit)
        trainingWindow.setTabOrder(self.saveWindowLengths1LineEdit, self.detectSpikes1But)
        trainingWindow.setTabOrder(self.detectSpikes1But, self.saveSpikes2LineEdit)
        trainingWindow.setTabOrder(self.saveSpikes2LineEdit, self.saveWindowLengths2LineEdit)
        trainingWindow.setTabOrder(self.saveWindowLengths2LineEdit, self.detectSpikes2But)
        trainingWindow.setTabOrder(self.detectSpikes2But, self.loadSpikes1LineEdit)
        trainingWindow.setTabOrder(self.loadSpikes1LineEdit, self.verifySpikes1But)
        trainingWindow.setTabOrder(self.verifySpikes1But, self.loadSpikes2LineEdit)
        trainingWindow.setTabOrder(self.loadSpikes2LineEdit, self.verifySpikes2But)
        trainingWindow.setTabOrder(self.verifySpikes2But, self.saveFeatures1LineEdit)
        trainingWindow.setTabOrder(self.saveFeatures1LineEdit, self.saveFeatures2LineEdit)
        trainingWindow.setTabOrder(self.saveFeatures2LineEdit, self.saveFilterLineEdit)
        trainingWindow.setTabOrder(self.saveFilterLineEdit, self.saveRescaleLineEdit)
        trainingWindow.setTabOrder(self.saveRescaleLineEdit, self.numberFeaturesLineEdit)
        trainingWindow.setTabOrder(self.numberFeaturesLineEdit, self.extractFeaturesBut)
        trainingWindow.setTabOrder(self.extractFeaturesBut, self.loadFeatures1LineEdit)
        trainingWindow.setTabOrder(self.loadFeatures1LineEdit, self.loadFeatures2LineEdit)
        trainingWindow.setTabOrder(self.loadFeatures2LineEdit, self.trainingNumberSamplesFish1LineEdit)
        trainingWindow.setTabOrder(self.trainingNumberSamplesFish1LineEdit, self.trainingProbabilityFish1LineEdit)
        trainingWindow.setTabOrder(self.trainingProbabilityFish1LineEdit, self.trainingSaveFish1LineEdit)
        trainingWindow.setTabOrder(self.trainingSaveFish1LineEdit, self.trainingLoadFish1LineEdit)
        trainingWindow.setTabOrder(self.trainingLoadFish1LineEdit, self.crossNumberSamplesFish1LineEdit)
        trainingWindow.setTabOrder(self.crossNumberSamplesFish1LineEdit, self.crossProbabilityFish1LineEdit)
        trainingWindow.setTabOrder(self.crossProbabilityFish1LineEdit, self.crossSaveFish1LineEdit)
        trainingWindow.setTabOrder(self.crossSaveFish1LineEdit, self.crossLoadFish1LineEdit)
        trainingWindow.setTabOrder(self.crossLoadFish1LineEdit, self.testingNumberSamplesFish1LineEdit)
        trainingWindow.setTabOrder(self.testingNumberSamplesFish1LineEdit, self.testingProbabilityFish1LineEdit)
        trainingWindow.setTabOrder(self.testingProbabilityFish1LineEdit, self.testingSaveFish1LineEdit)
        trainingWindow.setTabOrder(self.testingSaveFish1LineEdit, self.testingLoadFish1LineEdit)
        trainingWindow.setTabOrder(self.testingLoadFish1LineEdit, self.sliceFish1But)
        trainingWindow.setTabOrder(self.sliceFish1But, self.tabWidget)
        trainingWindow.setTabOrder(self.tabWidget, self.trainingNumberSamplesFish2LineEdit)
        trainingWindow.setTabOrder(self.trainingNumberSamplesFish2LineEdit, self.trainingProbabilityFish2LineEdit)
        trainingWindow.setTabOrder(self.trainingProbabilityFish2LineEdit, self.trainingSaveFish2LineEdit)
        trainingWindow.setTabOrder(self.trainingSaveFish2LineEdit, self.trainingLoadFish2LineEdit)
        trainingWindow.setTabOrder(self.trainingLoadFish2LineEdit, self.crossNumberSamplesFish2LineEdit)
        trainingWindow.setTabOrder(self.crossNumberSamplesFish2LineEdit, self.crossProbabilityFish2LineEdit)
        trainingWindow.setTabOrder(self.crossProbabilityFish2LineEdit, self.crossSaveFish2LineEdit)
        trainingWindow.setTabOrder(self.crossSaveFish2LineEdit, self.crossLoadFish2LineEdit)
        trainingWindow.setTabOrder(self.crossLoadFish2LineEdit, self.testingNumberSamplesFish2LineEdit)
        trainingWindow.setTabOrder(self.testingNumberSamplesFish2LineEdit, self.testingProbabilityFish2LineEdit)
        trainingWindow.setTabOrder(self.testingProbabilityFish2LineEdit, self.testingSaveFish2LineEdit)
        trainingWindow.setTabOrder(self.testingSaveFish2LineEdit, self.testingLoadFish2LineEdit)
        trainingWindow.setTabOrder(self.testingLoadFish2LineEdit, self.sliceFish2But)
        trainingWindow.setTabOrder(self.sliceFish2But, self.defaultSVMValuesBut)
        trainingWindow.setTabOrder(self.defaultSVMValuesBut, self.cStartLineEdit)
        trainingWindow.setTabOrder(self.cStartLineEdit, self.cStopLineEdit)
        trainingWindow.setTabOrder(self.cStopLineEdit, self.cStepLineEdit)
        trainingWindow.setTabOrder(self.cStepLineEdit, self.cValueLineEdit)
        trainingWindow.setTabOrder(self.cValueLineEdit, self.gStartLineEdit)
        trainingWindow.setTabOrder(self.gStartLineEdit, self.gStopLineEdit)
        trainingWindow.setTabOrder(self.gStopLineEdit, self.gStepLineEdit)
        trainingWindow.setTabOrder(self.gStepLineEdit, self.gValueLineEdit)
        trainingWindow.setTabOrder(self.gValueLineEdit, self.optimizeSVMBut)
        trainingWindow.setTabOrder(self.optimizeSVMBut, self.saveSVMLineEdit)
        trainingWindow.setTabOrder(self.saveSVMLineEdit, self.trainSVMBut)
        trainingWindow.setTabOrder(self.trainSVMBut, self.loadSVMLineEdit)
        trainingWindow.setTabOrder(self.loadSVMLineEdit, self.generateROCBut)

    def retranslateUi(self, trainingWindow):
        trainingWindow.setWindowTitle(_translate("trainingWindow", "gymnotools - Training", None))
        self.step1TitleLabel.setText(_translate("trainingWindow", "1. Select parameters for spike detection >", None))
        self.thresholdLevelLabel.setText(_translate("trainingWindow", "Threshold level (V):", None))
        self.filterAssist2But.setText(_translate("trainingWindow", "Filter Assistant", None))
        self.spikeParametersFish2Label.setText(_translate("trainingWindow", "Fish 2", None))
        self.thresholdAssist1But.setText(_translate("trainingWindow", "Threshold Assistant", None))
        self.cutoffLabel.setText(_translate("trainingWindow", "Cutoff frequency (cycles/sample):", None))
        self.highSaturationLabel.setText(_translate("trainingWindow", "HIGH saturation level (V):", None))
        self.lowSaturationLabel.setText(_translate("trainingWindow", "LOW saturation level (V):", None))
        self.tapsLabel.setText(_translate("trainingWindow", "Number of taps:", None))
        self.loadTSLabel.setText(_translate("trainingWindow", "Load timeseries data:", None))
        self.thresholdAssist2But.setText(_translate("trainingWindow", "Threshold Assistant", None))
        self.spikeParametersFish1Label.setText(_translate("trainingWindow", "Fish 1", None))
        self.saturationLabel.setText(_translate("trainingWindow", "Saturation level:", None))
        self.thresholdLabel.setText(_translate("trainingWindow", "Threshold:", None))
        self.filterLabel.setText(_translate("trainingWindow", "Low-pass filter parameters:", None))
        self.filterAssist1But.setText(_translate("trainingWindow", "Filter Assistant", None))
        self.saveParametersBut.setText(_translate("trainingWindow", "Save parameters", None))
        self.loadParametersBut.setText(_translate("trainingWindow", "Load parameters", None))
        self.step2TitleLabel.setText(_translate("trainingWindow", "2. Detect Spikes >", None))
        self.saveSpikesLabel.setText(_translate("trainingWindow", "Save detected spikes as: ", None))
        self.saveWindowLengthsLabel.setText(_translate("trainingWindow", "Save window lengths as:", None))
        self.verifySpikes2But.setText(_translate("trainingWindow", "Verify detection", None))
        self.loadSpikesLabel.setText(_translate("trainingWindow", "Load spikes file:", None))
        self.onlyAboveLabel.setText(_translate("trainingWindow", "Only detect spikes above (V) (Needed to avoid noise)", None))
        self.detectFish2Label.setText(_translate("trainingWindow", "Fish 2", None))
        self.verifySpikes1But.setText(_translate("trainingWindow", "Verify detection", None))
        self.detectSpikes1But.setText(_translate("trainingWindow", "Detect Spikes", None))
        self.detectFish1Label.setText(_translate("trainingWindow", "Fish 1", None))
        self.detectSpikes2But.setText(_translate("trainingWindow", "Detect Spikes", None))
        self.step3TitleLabel.setText(_translate("trainingWindow", "3. Rescale and extract features >", None))
        self.saveRescaleLabel.setText(_translate("trainingWindow", "Save rescale as:", None))
        self.numberFeaturesLabel.setText(_translate("trainingWindow", "Number of features: ", None))
        self.saveFeaturesLabel.setText(_translate("trainingWindow", "Save features as:", None))
        self.loadFeaturesLabel.setText(_translate("trainingWindow", "Load features file: ", None))
        self.featuresFish1Label.setText(_translate("trainingWindow", "Fish 1", None))
        self.featuresFish2Label.setText(_translate("trainingWindow", "Fish 2", None))
        self.saveFilterLabel.setText(_translate("trainingWindow", "Save filter as:", None))
        self.numberFeaturesLineEdit.setText(_translate("trainingWindow", "20", None))
        self.extractFeaturesBut.setText(_translate("trainingWindow", "Extract features", None))
        self.step4TitleLabel.setText(_translate("trainingWindow", "4. Slice series to make training, cross validation and testing sets >", None))
        self.numberSamplesFish1Label.setText(_translate("trainingWindow", "Number of samples", None))
        self.probabilityFish1Label.setText(_translate("trainingWindow", "Probability of selection", None))
        self.saveSlicesFish1Label.setText(_translate("trainingWindow", "Save as:", None))
        self.loadSlicesFish1Label.setText(_translate("trainingWindow", "Load slice file:", None))
        self.trainingFish1Label.setText(_translate("trainingWindow", "Training set (About 10000 samples):", None))
        self.crossValidationFish1Label.setText(_translate("trainingWindow", "Cross validation set (About prob. 0.3):", None))
        self.testingFish1Label.setText(_translate("trainingWindow", "Testing set: ", None))
        self.sliceFish1But.setText(_translate("trainingWindow", "Slice", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFish1), _translate("trainingWindow", "Fish 1", None))
        self.numberSamplesFish2Label.setText(_translate("trainingWindow", "Number of samples", None))
        self.probabilityFish2Label.setText(_translate("trainingWindow", "Probability of selection", None))
        self.saveSlicesFish2Label.setText(_translate("trainingWindow", "Save as:", None))
        self.loadSlicesFish2Label.setText(_translate("trainingWindow", "Load slice file:", None))
        self.trainingFish2Label.setText(_translate("trainingWindow", "Training set (About 10000 samples):", None))
        self.crossValidationFish2Label.setText(_translate("trainingWindow", "Cross validation set (About prob. 0.3):", None))
        self.testingFish2Label.setText(_translate("trainingWindow", "Testing set: ", None))
        self.sliceFish2But.setText(_translate("trainingWindow", "Slice", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFish2), _translate("trainingWindow", "Fish 2", None))
        self.step5TitleLabel.setText(_translate("trainingWindow", "5. Train SVM >", None))
        self.defaultSVMValuesBut.setText(_translate("trainingWindow", "Default values", None))
        self.saveSVMLabel.setText(_translate("trainingWindow", "Save SVM model as: ", None))
        self.valueLabel.setText(_translate("trainingWindow", "Selected value", None))
        self.trainSVMBut.setText(_translate("trainingWindow", "Train SVM", None))
        self.startLabel.setText(_translate("trainingWindow", "Start", None))
        self.stopLabel.setText(_translate("trainingWindow", "Stop", None))
        self.gStopLineEdit.setText(_translate("trainingWindow", "3.0", None))
        self.cStepLineEdit.setText(_translate("trainingWindow", "2.0", None))
        self.gStartLineEdit.setText(_translate("trainingWindow", "-15.0", None))
        self.gStepLineEdit.setText(_translate("trainingWindow", "2.0", None))
        self.cLabel.setText(_translate("trainingWindow", "SVM C Parameter: ", None))
        self.cStartLineEdit.setText(_translate("trainingWindow", "-5.0", None))
        self.gLabel.setText(_translate("trainingWindow", "SVM Gamma Parameter: ", None))
        self.cStopLineEdit.setText(_translate("trainingWindow", "15.0", None))
        self.stepLabel.setText(_translate("trainingWindow", "Step", None))
        self.optimizeSVMBut.setText(_translate("trainingWindow", "Optimize Parameters", None))
        self.loadSVMLabel.setText(_translate("trainingWindow", "Load SVM model: ", None))
        self.generateROCBut.setText(_translate("trainingWindow", "Generate ROC Curve", None))

from PyKDE4.kdeui import KPixmapRegionSelectorWidget
from clickAux import ClickQLineEdit, ClickQLabel
from ROCAux import ROCWidget
