# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'training_interface.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_trainingWindow(object):
    def setupUi(self, trainingWindow):
        trainingWindow.setObjectName("trainingWindow")
        trainingWindow.setWindowModality(QtCore.Qt.WindowModal)
        trainingWindow.resize(1117, 719)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(trainingWindow.sizePolicy().hasHeightForWidth())
        trainingWindow.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(trainingWindow)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(trainingWindow)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1438, 1118))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.step1Layout = QtWidgets.QVBoxLayout()
        self.step1Layout.setObjectName("step1Layout")
        self.step1TitleLabel = ClickQLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.step1TitleLabel.setFont(font)
        self.step1TitleLabel.setObjectName("step1TitleLabel")
        self.step1Layout.addWidget(self.step1TitleLabel)
        self.step1ParametersLayout = QtWidgets.QGridLayout()
        self.step1ParametersLayout.setObjectName("step1ParametersLayout")
        self.lowCutoffLineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.lowCutoffLineEdit.setObjectName("lowCutoffLineEdit")
        self.step1ParametersLayout.addWidget(self.lowCutoffLineEdit, 5, 1, 1, 1)
        self.gmeanLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.gmeanLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.gmeanLabel.setObjectName("gmeanLabel")
        self.step1ParametersLayout.addWidget(self.gmeanLabel, 3, 0, 1, 1)
        self.filterLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setBold(True)
        font.setWeight(75)
        self.filterLabel.setFont(font)
        self.filterLabel.setObjectName("filterLabel")
        self.step1ParametersLayout.addWidget(self.filterLabel, 2, 0, 1, 1)
        self.SaveLoadHilbLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.SaveLoadHilbLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.SaveLoadHilbLabel.setObjectName("SaveLoadHilbLabel")
        self.step1ParametersLayout.addWidget(self.SaveLoadHilbLabel, 9, 0, 1, 1)
        self.cutoffLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.cutoffLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.cutoffLabel.setObjectName("cutoffLabel")
        self.step1ParametersLayout.addWidget(self.cutoffLabel, 5, 0, 1, 1)
        self.saveHilb1LineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.saveHilb1LineEdit.setObjectName("saveHilb1LineEdit")
        self.step1ParametersLayout.addWidget(self.saveHilb1LineEdit, 9, 1, 1, 1)
        self.UseExistingHilb = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.UseExistingHilb.setText("")
        self.UseExistingHilb.setObjectName("UseExistingHilb")
        self.step1ParametersLayout.addWidget(self.UseExistingHilb, 10, 0, 1, 1)
        self.saveHilb2LineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.saveHilb2LineEdit.setObjectName("saveHilb2LineEdit")
        self.step1ParametersLayout.addWidget(self.saveHilb2LineEdit, 9, 2, 1, 1)
        self.highCutoffLineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.highCutoffLineEdit.setObjectName("highCutoffLineEdit")
        self.step1ParametersLayout.addWidget(self.highCutoffLineEdit, 5, 2, 1, 1)
        self.loadTS2LineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.loadTS2LineEdit.setObjectName("loadTS2LineEdit")
        self.step1ParametersLayout.addWidget(self.loadTS2LineEdit, 8, 2, 1, 1)
        self.tapsLineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.tapsLineEdit.setObjectName("tapsLineEdit")
        self.step1ParametersLayout.addWidget(self.tapsLineEdit, 4, 1, 1, 2)
        self.loadTS1LineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.loadTS1LineEdit.setObjectName("loadTS1LineEdit")
        self.step1ParametersLayout.addWidget(self.loadTS1LineEdit, 8, 1, 1, 1)
        self.hilb2But = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.hilb2But.setObjectName("hilb2But")
        self.step1ParametersLayout.addWidget(self.hilb2But, 10, 2, 1, 1)
        self.tapsLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.tapsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.tapsLabel.setObjectName("tapsLabel")
        self.step1ParametersLayout.addWidget(self.tapsLabel, 4, 0, 1, 1)
        self.hilb1But = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.hilb1But.setObjectName("hilb1But")
        self.step1ParametersLayout.addWidget(self.hilb1But, 10, 1, 1, 1)
        self.loadTSLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.loadTSLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.loadTSLabel.setObjectName("loadTSLabel")
        self.step1ParametersLayout.addWidget(self.loadTSLabel, 8, 0, 1, 1)
        self.spikeParametersFish2Label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.spikeParametersFish2Label.setAlignment(QtCore.Qt.AlignCenter)
        self.spikeParametersFish2Label.setObjectName("spikeParametersFish2Label")
        self.step1ParametersLayout.addWidget(self.spikeParametersFish2Label, 7, 2, 1, 1)
        self.hilbLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.hilbLabel.setFont(font)
        self.hilbLabel.setObjectName("hilbLabel")
        self.step1ParametersLayout.addWidget(self.hilbLabel, 7, 0, 1, 1)
        self.spikeParametersFish1Label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.spikeParametersFish1Label.setAlignment(QtCore.Qt.AlignCenter)
        self.spikeParametersFish1Label.setObjectName("spikeParametersFish1Label")
        self.step1ParametersLayout.addWidget(self.spikeParametersFish1Label, 7, 1, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.step1ParametersLayout.addWidget(self.line_6, 6, 0, 1, 3)
        self.gmeanLineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.gmeanLineEdit.setObjectName("gmeanLineEdit")
        self.step1ParametersLayout.addWidget(self.gmeanLineEdit, 3, 1, 1, 2)
        self.step1Layout.addLayout(self.step1ParametersLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.step1Layout.addItem(spacerItem)
        self.gridLayout_2.addLayout(self.step1Layout, 1, 0, 1, 1)
        self.saveLoadParametersLayout = QtWidgets.QHBoxLayout()
        self.saveLoadParametersLayout.setObjectName("saveLoadParametersLayout")
        self.saveParametersBut = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.saveParametersBut.setObjectName("saveParametersBut")
        self.saveLoadParametersLayout.addWidget(self.saveParametersBut)
        self.loadParametersBut = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.loadParametersBut.setObjectName("loadParametersBut")
        self.saveLoadParametersLayout.addWidget(self.loadParametersBut)
        self.gridLayout_2.addLayout(self.saveLoadParametersLayout, 0, 0, 1, 5)
        self.line_0 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_0.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_0.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_0.setObjectName("line_0")
        self.gridLayout_2.addWidget(self.line_0, 1, 1, 1, 1)
        self.step2Layout = QtWidgets.QVBoxLayout()
        self.step2Layout.setObjectName("step2Layout")
        self.step2TitleLabel = ClickQLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.step2TitleLabel.setFont(font)
        self.step2TitleLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.step2TitleLabel.setObjectName("step2TitleLabel")
        self.step2Layout.addWidget(self.step2TitleLabel)
        self.step2ParametersLayout = QtWidgets.QGridLayout()
        self.step2ParametersLayout.setHorizontalSpacing(6)
        self.step2ParametersLayout.setVerticalSpacing(0)
        self.step2ParametersLayout.setObjectName("step2ParametersLayout")
        self.onlyAboveLineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.onlyAboveLineEdit.setObjectName("onlyAboveLineEdit")
        self.step2ParametersLayout.addWidget(self.onlyAboveLineEdit, 10, 0, 1, 3)
        self.loadHilb1LineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.loadHilb1LineEdit.setText("")
        self.loadHilb1LineEdit.setObjectName("loadHilb1LineEdit")
        self.step2ParametersLayout.addWidget(self.loadHilb1LineEdit, 14, 0, 2, 2)
        self.toleranceLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.toleranceLabel.setObjectName("toleranceLabel")
        self.step2ParametersLayout.addWidget(self.toleranceLabel, 7, 0, 1, 3)
        self.detectFish2Label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.detectFish2Label.setAlignment(QtCore.Qt.AlignCenter)
        self.detectFish2Label.setObjectName("detectFish2Label")
        self.step2ParametersLayout.addWidget(self.detectFish2Label, 12, 2, 1, 1)
        self.subSampLineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.subSampLineEdit.setObjectName("subSampLineEdit")
        self.step2ParametersLayout.addWidget(self.subSampLineEdit, 3, 0, 1, 1)
        self.saveSpikes1LineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.saveSpikes1LineEdit.setObjectName("saveSpikes1LineEdit")
        self.step2ParametersLayout.addWidget(self.saveSpikes1LineEdit, 22, 0, 1, 2)
        self.thresholdLevelLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.thresholdLevelLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.thresholdLevelLabel.setObjectName("thresholdLevelLabel")
        self.step2ParametersLayout.addWidget(self.thresholdLevelLabel, 13, 0, 1, 3, QtCore.Qt.AlignLeft)
        self.loadHilb2LineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.loadHilb2LineEdit.setText("")
        self.loadHilb2LineEdit.setObjectName("loadHilb2LineEdit")
        self.step2ParametersLayout.addWidget(self.loadHilb2LineEdit, 14, 2, 1, 1)
        self.verifySpikes1But = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.verifySpikes1But.setObjectName("verifySpikes1But")
        self.step2ParametersLayout.addWidget(self.verifySpikes1But, 29, 0, 1, 2)
        self.saveSpikes2LineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.saveSpikes2LineEdit.setObjectName("saveSpikes2LineEdit")
        self.step2ParametersLayout.addWidget(self.saveSpikes2LineEdit, 22, 2, 1, 1)
        self.waveletLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.waveletLabel.setObjectName("waveletLabel")
        self.step2ParametersLayout.addWidget(self.waveletLabel, 2, 2, 1, 1)
        self.loadSpikes2LineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.loadSpikes2LineEdit.setObjectName("loadSpikes2LineEdit")
        self.step2ParametersLayout.addWidget(self.loadSpikes2LineEdit, 28, 2, 1, 1)
        self.loadSpikesLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.loadSpikesLabel.setObjectName("loadSpikesLabel")
        self.step2ParametersLayout.addWidget(self.loadSpikesLabel, 27, 0, 1, 3)
        self.detectSpikes2But = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.detectSpikes2But.setObjectName("detectSpikes2But")
        self.step2ParametersLayout.addWidget(self.detectSpikes2But, 25, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.step2ParametersLayout.addItem(spacerItem1, 26, 0, 1, 3)
        self.verifySpikes2But = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.verifySpikes2But.setObjectName("verifySpikes2But")
        self.step2ParametersLayout.addWidget(self.verifySpikes2But, 29, 2, 1, 1)
        self.detectSpikes1But = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.detectSpikes1But.setObjectName("detectSpikes1But")
        self.step2ParametersLayout.addWidget(self.detectSpikes1But, 25, 0, 1, 2)
        self.loadSpikes1LineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.loadSpikes1LineEdit.setObjectName("loadSpikes1LineEdit")
        self.step2ParametersLayout.addWidget(self.loadSpikes1LineEdit, 28, 0, 1, 2)
        self.subsampLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.subsampLabel.setObjectName("subsampLabel")
        self.step2ParametersLayout.addWidget(self.subsampLabel, 2, 0, 1, 1)
        self.peakLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.peakLabel.setObjectName("peakLabel")
        self.step2ParametersLayout.addWidget(self.peakLabel, 2, 1, 1, 1)
        self.detectFish1Label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.detectFish1Label.setAlignment(QtCore.Qt.AlignCenter)
        self.detectFish1Label.setObjectName("detectFish1Label")
        self.step2ParametersLayout.addWidget(self.detectFish1Label, 12, 0, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.minWaveletLineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.minWaveletLineEdit.setObjectName("minWaveletLineEdit")
        self.horizontalLayout.addWidget(self.minWaveletLineEdit)
        self.maxWaveletLineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.maxWaveletLineEdit.setObjectName("maxWaveletLineEdit")
        self.horizontalLayout.addWidget(self.maxWaveletLineEdit)
        self.stepWaveletLineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.stepWaveletLineEdit.setObjectName("stepWaveletLineEdit")
        self.horizontalLayout.addWidget(self.stepWaveletLineEdit)
        self.step2ParametersLayout.addLayout(self.horizontalLayout, 3, 2, 1, 1)
        self.peakLineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.peakLineEdit.setObjectName("peakLineEdit")
        self.step2ParametersLayout.addWidget(self.peakLineEdit, 3, 1, 1, 1)
        self.toleranceLineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.toleranceLineEdit.setObjectName("toleranceLineEdit")
        self.step2ParametersLayout.addWidget(self.toleranceLineEdit, 8, 0, 1, 3)
        self.minHilbLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.minHilbLabel.setObjectName("minHilbLabel")
        self.step2ParametersLayout.addWidget(self.minHilbLabel, 4, 0, 1, 2)
        self.onlyAboveLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.onlyAboveLabel.setObjectName("onlyAboveLabel")
        self.step2ParametersLayout.addWidget(self.onlyAboveLabel, 9, 0, 1, 3)
        self.saveSpikesLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.saveSpikesLabel.setObjectName("saveSpikesLabel")
        self.step2ParametersLayout.addWidget(self.saveSpikesLabel, 20, 0, 2, 3)
        self.minHilbLineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.minHilbLineEdit.setObjectName("minHilbLineEdit")
        self.step2ParametersLayout.addWidget(self.minHilbLineEdit, 5, 0, 1, 3)
        self.line = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.step2ParametersLayout.addWidget(self.line, 11, 0, 1, 3)
        self.step2ParametersLayout.setColumnStretch(0, 4)
        self.step2Layout.addLayout(self.step2ParametersLayout)
        self.gridLayout_2.addLayout(self.step2Layout, 1, 2, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_2.addWidget(self.line_4, 1, 3, 1, 1)
        self.step3Layout = QtWidgets.QVBoxLayout()
        self.step3Layout.setObjectName("step3Layout")
        self.step3TitleLabel = ClickQLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.step3TitleLabel.setFont(font)
        self.step3TitleLabel.setObjectName("step3TitleLabel")
        self.step3Layout.addWidget(self.step3TitleLabel)
        self.step3ParametersLayout = QtWidgets.QGridLayout()
        self.step3ParametersLayout.setObjectName("step3ParametersLayout")
        self.saveRescaleLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.saveRescaleLabel.setObjectName("saveRescaleLabel")
        self.step3ParametersLayout.addWidget(self.saveRescaleLabel, 5, 0, 1, 1)
        self.numberFeaturesLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.numberFeaturesLabel.setObjectName("numberFeaturesLabel")
        self.step3ParametersLayout.addWidget(self.numberFeaturesLabel, 7, 0, 1, 2)
        self.saveFeaturesLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.saveFeaturesLabel.setObjectName("saveFeaturesLabel")
        self.step3ParametersLayout.addWidget(self.saveFeaturesLabel, 1, 0, 1, 2)
        self.loadFeaturesLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.loadFeaturesLabel.setObjectName("loadFeaturesLabel")
        self.step3ParametersLayout.addWidget(self.loadFeaturesLabel, 12, 0, 1, 2)
        self.featuresFish1Label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.featuresFish1Label.setAlignment(QtCore.Qt.AlignCenter)
        self.featuresFish1Label.setObjectName("featuresFish1Label")
        self.step3ParametersLayout.addWidget(self.featuresFish1Label, 0, 0, 1, 1)
        self.featuresFish2Label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.featuresFish2Label.setAlignment(QtCore.Qt.AlignCenter)
        self.featuresFish2Label.setObjectName("featuresFish2Label")
        self.step3ParametersLayout.addWidget(self.featuresFish2Label, 0, 1, 1, 1)
        self.saveFeatures1LineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.saveFeatures1LineEdit.setObjectName("saveFeatures1LineEdit")
        self.step3ParametersLayout.addWidget(self.saveFeatures1LineEdit, 2, 0, 1, 1)
        self.saveFeatures2LineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.saveFeatures2LineEdit.setObjectName("saveFeatures2LineEdit")
        self.step3ParametersLayout.addWidget(self.saveFeatures2LineEdit, 2, 1, 1, 1)
        self.loadFeatures1LineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.loadFeatures1LineEdit.setObjectName("loadFeatures1LineEdit")
        self.step3ParametersLayout.addWidget(self.loadFeatures1LineEdit, 13, 0, 1, 1)
        self.loadFeatures2LineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.loadFeatures2LineEdit.setObjectName("loadFeatures2LineEdit")
        self.step3ParametersLayout.addWidget(self.loadFeatures2LineEdit, 13, 1, 1, 1)
        self.saveFilterLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.saveFilterLabel.setObjectName("saveFilterLabel")
        self.step3ParametersLayout.addWidget(self.saveFilterLabel, 3, 0, 1, 1)
        self.saveFilterLineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.saveFilterLineEdit.setObjectName("saveFilterLineEdit")
        self.step3ParametersLayout.addWidget(self.saveFilterLineEdit, 4, 0, 1, 2)
        self.numberFeaturesLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.numberFeaturesLineEdit.setObjectName("numberFeaturesLineEdit")
        self.step3ParametersLayout.addWidget(self.numberFeaturesLineEdit, 8, 0, 1, 2)
        self.extractFeaturesBut = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.extractFeaturesBut.setObjectName("extractFeaturesBut")
        self.step3ParametersLayout.addWidget(self.extractFeaturesBut, 10, 0, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.step3ParametersLayout.addItem(spacerItem2, 11, 0, 1, 2)
        self.saveRescaleLineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.saveRescaleLineEdit.setObjectName("saveRescaleLineEdit")
        self.step3ParametersLayout.addWidget(self.saveRescaleLineEdit, 6, 0, 1, 2)
        self.step3Layout.addLayout(self.step3ParametersLayout)
        self.step3Layout.setStretch(1, 4)
        self.gridLayout_2.addLayout(self.step3Layout, 1, 4, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 2, 0, 1, 5)
        self.step4Layout = QtWidgets.QVBoxLayout()
        self.step4Layout.setObjectName("step4Layout")
        self.step4TitleLabel = ClickQLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.step4TitleLabel.setFont(font)
        self.step4TitleLabel.setObjectName("step4TitleLabel")
        self.step4Layout.addWidget(self.step4TitleLabel)
        self.tabWidget = QtWidgets.QTabWidget(self.scrollAreaWidgetContents)
        self.tabWidget.setObjectName("tabWidget")
        self.tabFish1 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabFish1.sizePolicy().hasHeightForWidth())
        self.tabFish1.setSizePolicy(sizePolicy)
        self.tabFish1.setObjectName("tabFish1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tabFish1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.sliceInfoFish1Label = QtWidgets.QLabel(self.tabFish1)
        self.sliceInfoFish1Label.setText("")
        self.sliceInfoFish1Label.setObjectName("sliceInfoFish1Label")
        self.gridLayout_3.addWidget(self.sliceInfoFish1Label, 0, 0, 1, 1)
        self.numberSamplesFish1Label = QtWidgets.QLabel(self.tabFish1)
        self.numberSamplesFish1Label.setAlignment(QtCore.Qt.AlignCenter)
        self.numberSamplesFish1Label.setObjectName("numberSamplesFish1Label")
        self.gridLayout_3.addWidget(self.numberSamplesFish1Label, 1, 1, 1, 1)
        self.probabilityFish1Label = QtWidgets.QLabel(self.tabFish1)
        self.probabilityFish1Label.setAlignment(QtCore.Qt.AlignCenter)
        self.probabilityFish1Label.setObjectName("probabilityFish1Label")
        self.gridLayout_3.addWidget(self.probabilityFish1Label, 1, 2, 1, 1)
        self.saveSlicesFish1Label = QtWidgets.QLabel(self.tabFish1)
        self.saveSlicesFish1Label.setAlignment(QtCore.Qt.AlignCenter)
        self.saveSlicesFish1Label.setObjectName("saveSlicesFish1Label")
        self.gridLayout_3.addWidget(self.saveSlicesFish1Label, 1, 3, 1, 1)
        self.loadSlicesFish1Label = QtWidgets.QLabel(self.tabFish1)
        self.loadSlicesFish1Label.setAlignment(QtCore.Qt.AlignCenter)
        self.loadSlicesFish1Label.setObjectName("loadSlicesFish1Label")
        self.gridLayout_3.addWidget(self.loadSlicesFish1Label, 1, 4, 1, 1)
        self.trainingFish1Label = QtWidgets.QLabel(self.tabFish1)
        self.trainingFish1Label.setObjectName("trainingFish1Label")
        self.gridLayout_3.addWidget(self.trainingFish1Label, 2, 0, 1, 1)
        self.trainingNumberSamplesFish1LineEdit = QtWidgets.QLineEdit(self.tabFish1)
        self.trainingNumberSamplesFish1LineEdit.setObjectName("trainingNumberSamplesFish1LineEdit")
        self.gridLayout_3.addWidget(self.trainingNumberSamplesFish1LineEdit, 2, 1, 1, 1)
        self.trainingProbabilityFish1LineEdit = QtWidgets.QLineEdit(self.tabFish1)
        self.trainingProbabilityFish1LineEdit.setObjectName("trainingProbabilityFish1LineEdit")
        self.gridLayout_3.addWidget(self.trainingProbabilityFish1LineEdit, 2, 2, 1, 1)
        self.trainingSaveFish1LineEdit = ClickQLineEdit(self.tabFish1)
        self.trainingSaveFish1LineEdit.setObjectName("trainingSaveFish1LineEdit")
        self.gridLayout_3.addWidget(self.trainingSaveFish1LineEdit, 2, 3, 1, 1)
        self.trainingLoadFish1LineEdit = ClickQLineEdit(self.tabFish1)
        self.trainingLoadFish1LineEdit.setObjectName("trainingLoadFish1LineEdit")
        self.gridLayout_3.addWidget(self.trainingLoadFish1LineEdit, 2, 4, 1, 1)
        self.crossValidationFish1Label = QtWidgets.QLabel(self.tabFish1)
        self.crossValidationFish1Label.setObjectName("crossValidationFish1Label")
        self.gridLayout_3.addWidget(self.crossValidationFish1Label, 3, 0, 1, 1)
        self.crossNumberSamplesFish1LineEdit = QtWidgets.QLineEdit(self.tabFish1)
        self.crossNumberSamplesFish1LineEdit.setObjectName("crossNumberSamplesFish1LineEdit")
        self.gridLayout_3.addWidget(self.crossNumberSamplesFish1LineEdit, 3, 1, 1, 1)
        self.crossProbabilityFish1LineEdit = QtWidgets.QLineEdit(self.tabFish1)
        self.crossProbabilityFish1LineEdit.setObjectName("crossProbabilityFish1LineEdit")
        self.gridLayout_3.addWidget(self.crossProbabilityFish1LineEdit, 3, 2, 1, 1)
        self.crossSaveFish1LineEdit = ClickQLineEdit(self.tabFish1)
        self.crossSaveFish1LineEdit.setObjectName("crossSaveFish1LineEdit")
        self.gridLayout_3.addWidget(self.crossSaveFish1LineEdit, 3, 3, 1, 1)
        self.crossLoadFish1LineEdit = ClickQLineEdit(self.tabFish1)
        self.crossLoadFish1LineEdit.setObjectName("crossLoadFish1LineEdit")
        self.gridLayout_3.addWidget(self.crossLoadFish1LineEdit, 3, 4, 1, 1)
        self.testingFish1Label = QtWidgets.QLabel(self.tabFish1)
        self.testingFish1Label.setObjectName("testingFish1Label")
        self.gridLayout_3.addWidget(self.testingFish1Label, 4, 0, 1, 1)
        self.testingNumberSamplesFish1LineEdit = QtWidgets.QLineEdit(self.tabFish1)
        self.testingNumberSamplesFish1LineEdit.setObjectName("testingNumberSamplesFish1LineEdit")
        self.gridLayout_3.addWidget(self.testingNumberSamplesFish1LineEdit, 4, 1, 1, 1)
        self.testingProbabilityFish1LineEdit = QtWidgets.QLineEdit(self.tabFish1)
        self.testingProbabilityFish1LineEdit.setObjectName("testingProbabilityFish1LineEdit")
        self.gridLayout_3.addWidget(self.testingProbabilityFish1LineEdit, 4, 2, 1, 1)
        self.testingSaveFish1LineEdit = ClickQLineEdit(self.tabFish1)
        self.testingSaveFish1LineEdit.setObjectName("testingSaveFish1LineEdit")
        self.gridLayout_3.addWidget(self.testingSaveFish1LineEdit, 4, 3, 1, 1)
        self.testingLoadFish1LineEdit = ClickQLineEdit(self.tabFish1)
        self.testingLoadFish1LineEdit.setObjectName("testingLoadFish1LineEdit")
        self.gridLayout_3.addWidget(self.testingLoadFish1LineEdit, 4, 4, 1, 1)
        self.sliceFish1But = QtWidgets.QPushButton(self.tabFish1)
        self.sliceFish1But.setObjectName("sliceFish1But")
        self.gridLayout_3.addWidget(self.sliceFish1But, 5, 0, 1, 5)
        spacerItem3 = QtWidgets.QSpacerItem(204, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tabFish1, "")
        self.tabFish2 = QtWidgets.QWidget()
        self.tabFish2.setObjectName("tabFish2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tabFish2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.sliceInfoFish2Label = QtWidgets.QLabel(self.tabFish2)
        self.sliceInfoFish2Label.setText("")
        self.sliceInfoFish2Label.setObjectName("sliceInfoFish2Label")
        self.gridLayout_4.addWidget(self.sliceInfoFish2Label, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(204, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem4, 1, 0, 1, 1)
        self.numberSamplesFish2Label = QtWidgets.QLabel(self.tabFish2)
        self.numberSamplesFish2Label.setAlignment(QtCore.Qt.AlignCenter)
        self.numberSamplesFish2Label.setObjectName("numberSamplesFish2Label")
        self.gridLayout_4.addWidget(self.numberSamplesFish2Label, 1, 1, 1, 1)
        self.probabilityFish2Label = QtWidgets.QLabel(self.tabFish2)
        self.probabilityFish2Label.setAlignment(QtCore.Qt.AlignCenter)
        self.probabilityFish2Label.setObjectName("probabilityFish2Label")
        self.gridLayout_4.addWidget(self.probabilityFish2Label, 1, 2, 1, 1)
        self.saveSlicesFish2Label = QtWidgets.QLabel(self.tabFish2)
        self.saveSlicesFish2Label.setAlignment(QtCore.Qt.AlignCenter)
        self.saveSlicesFish2Label.setObjectName("saveSlicesFish2Label")
        self.gridLayout_4.addWidget(self.saveSlicesFish2Label, 1, 3, 1, 1)
        self.loadSlicesFish2Label = QtWidgets.QLabel(self.tabFish2)
        self.loadSlicesFish2Label.setAlignment(QtCore.Qt.AlignCenter)
        self.loadSlicesFish2Label.setObjectName("loadSlicesFish2Label")
        self.gridLayout_4.addWidget(self.loadSlicesFish2Label, 1, 4, 1, 1)
        self.trainingFish2Label = QtWidgets.QLabel(self.tabFish2)
        self.trainingFish2Label.setObjectName("trainingFish2Label")
        self.gridLayout_4.addWidget(self.trainingFish2Label, 2, 0, 1, 1)
        self.trainingNumberSamplesFish2LineEdit = QtWidgets.QLineEdit(self.tabFish2)
        self.trainingNumberSamplesFish2LineEdit.setObjectName("trainingNumberSamplesFish2LineEdit")
        self.gridLayout_4.addWidget(self.trainingNumberSamplesFish2LineEdit, 2, 1, 1, 1)
        self.trainingProbabilityFish2LineEdit = QtWidgets.QLineEdit(self.tabFish2)
        self.trainingProbabilityFish2LineEdit.setObjectName("trainingProbabilityFish2LineEdit")
        self.gridLayout_4.addWidget(self.trainingProbabilityFish2LineEdit, 2, 2, 1, 1)
        self.trainingSaveFish2LineEdit = ClickQLineEdit(self.tabFish2)
        self.trainingSaveFish2LineEdit.setObjectName("trainingSaveFish2LineEdit")
        self.gridLayout_4.addWidget(self.trainingSaveFish2LineEdit, 2, 3, 1, 1)
        self.trainingLoadFish2LineEdit = ClickQLineEdit(self.tabFish2)
        self.trainingLoadFish2LineEdit.setObjectName("trainingLoadFish2LineEdit")
        self.gridLayout_4.addWidget(self.trainingLoadFish2LineEdit, 2, 4, 1, 1)
        self.crossValidationFish2Label = QtWidgets.QLabel(self.tabFish2)
        self.crossValidationFish2Label.setObjectName("crossValidationFish2Label")
        self.gridLayout_4.addWidget(self.crossValidationFish2Label, 3, 0, 1, 1)
        self.crossNumberSamplesFish2LineEdit = QtWidgets.QLineEdit(self.tabFish2)
        self.crossNumberSamplesFish2LineEdit.setObjectName("crossNumberSamplesFish2LineEdit")
        self.gridLayout_4.addWidget(self.crossNumberSamplesFish2LineEdit, 3, 1, 1, 1)
        self.crossProbabilityFish2LineEdit = QtWidgets.QLineEdit(self.tabFish2)
        self.crossProbabilityFish2LineEdit.setObjectName("crossProbabilityFish2LineEdit")
        self.gridLayout_4.addWidget(self.crossProbabilityFish2LineEdit, 3, 2, 1, 1)
        self.crossSaveFish2LineEdit = ClickQLineEdit(self.tabFish2)
        self.crossSaveFish2LineEdit.setObjectName("crossSaveFish2LineEdit")
        self.gridLayout_4.addWidget(self.crossSaveFish2LineEdit, 3, 3, 1, 1)
        self.crossLoadFish2LineEdit = ClickQLineEdit(self.tabFish2)
        self.crossLoadFish2LineEdit.setObjectName("crossLoadFish2LineEdit")
        self.gridLayout_4.addWidget(self.crossLoadFish2LineEdit, 3, 4, 1, 1)
        self.testingFish2Label = QtWidgets.QLabel(self.tabFish2)
        self.testingFish2Label.setObjectName("testingFish2Label")
        self.gridLayout_4.addWidget(self.testingFish2Label, 4, 0, 1, 1)
        self.testingNumberSamplesFish2LineEdit = QtWidgets.QLineEdit(self.tabFish2)
        self.testingNumberSamplesFish2LineEdit.setObjectName("testingNumberSamplesFish2LineEdit")
        self.gridLayout_4.addWidget(self.testingNumberSamplesFish2LineEdit, 4, 1, 1, 1)
        self.testingProbabilityFish2LineEdit = QtWidgets.QLineEdit(self.tabFish2)
        self.testingProbabilityFish2LineEdit.setObjectName("testingProbabilityFish2LineEdit")
        self.gridLayout_4.addWidget(self.testingProbabilityFish2LineEdit, 4, 2, 1, 1)
        self.testingSaveFish2LineEdit = ClickQLineEdit(self.tabFish2)
        self.testingSaveFish2LineEdit.setObjectName("testingSaveFish2LineEdit")
        self.gridLayout_4.addWidget(self.testingSaveFish2LineEdit, 4, 3, 1, 1)
        self.testingLoadFish2LineEdit = ClickQLineEdit(self.tabFish2)
        self.testingLoadFish2LineEdit.setObjectName("testingLoadFish2LineEdit")
        self.gridLayout_4.addWidget(self.testingLoadFish2LineEdit, 4, 4, 1, 1)
        self.sliceFish2But = QtWidgets.QPushButton(self.tabFish2)
        self.sliceFish2But.setObjectName("sliceFish2But")
        self.gridLayout_4.addWidget(self.sliceFish2But, 5, 0, 1, 5)
        self.tabWidget.addTab(self.tabFish2, "")
        self.step4Layout.addWidget(self.tabWidget)
        self.gridLayout_2.addLayout(self.step4Layout, 3, 0, 1, 5)
        self.line_1 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_1.setObjectName("line_1")
        self.gridLayout_2.addWidget(self.line_1, 4, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_2.addWidget(self.line_3, 4, 2, 1, 3)
        self.step5Layout = QtWidgets.QVBoxLayout()
        self.step5Layout.setObjectName("step5Layout")
        self.step5TitleLabel = ClickQLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.step5TitleLabel.setFont(font)
        self.step5TitleLabel.setObjectName("step5TitleLabel")
        self.step5Layout.addWidget(self.step5TitleLabel)
        self.step5ParametersLayout = QtWidgets.QGridLayout()
        self.step5ParametersLayout.setObjectName("step5ParametersLayout")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.step5ParametersLayout.addItem(spacerItem5, 1, 0, 1, 1)
        self.defaultSVMValuesBut = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.defaultSVMValuesBut.setObjectName("defaultSVMValuesBut")
        self.step5ParametersLayout.addWidget(self.defaultSVMValuesBut, 0, 0, 1, 5)
        self.saveSVMLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.saveSVMLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.saveSVMLabel.setObjectName("saveSVMLabel")
        self.step5ParametersLayout.addWidget(self.saveSVMLabel, 5, 0, 1, 1)
        self.valueLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.valueLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.valueLabel.setObjectName("valueLabel")
        self.step5ParametersLayout.addWidget(self.valueLabel, 1, 4, 1, 1)
        self.trainSVMBut = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.trainSVMBut.setObjectName("trainSVMBut")
        self.step5ParametersLayout.addWidget(self.trainSVMBut, 6, 0, 1, 5)
        self.startLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.startLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.startLabel.setObjectName("startLabel")
        self.step5ParametersLayout.addWidget(self.startLabel, 1, 1, 1, 1)
        self.stopLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.stopLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.stopLabel.setObjectName("stopLabel")
        self.step5ParametersLayout.addWidget(self.stopLabel, 1, 2, 1, 1)
        self.gStopLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.gStopLineEdit.setObjectName("gStopLineEdit")
        self.step5ParametersLayout.addWidget(self.gStopLineEdit, 3, 2, 1, 1)
        self.saveSVMLineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.saveSVMLineEdit.setObjectName("saveSVMLineEdit")
        self.step5ParametersLayout.addWidget(self.saveSVMLineEdit, 5, 1, 1, 4)
        self.cStepLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.cStepLineEdit.setObjectName("cStepLineEdit")
        self.step5ParametersLayout.addWidget(self.cStepLineEdit, 2, 3, 1, 1)
        self.cValueLineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.cValueLineEdit.setObjectName("cValueLineEdit")
        self.step5ParametersLayout.addWidget(self.cValueLineEdit, 2, 4, 1, 1)
        self.gStartLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.gStartLineEdit.setObjectName("gStartLineEdit")
        self.step5ParametersLayout.addWidget(self.gStartLineEdit, 3, 1, 1, 1)
        self.gStepLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.gStepLineEdit.setObjectName("gStepLineEdit")
        self.step5ParametersLayout.addWidget(self.gStepLineEdit, 3, 3, 1, 1)
        self.cLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.cLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.cLabel.setObjectName("cLabel")
        self.step5ParametersLayout.addWidget(self.cLabel, 2, 0, 1, 1)
        self.gValueLineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.gValueLineEdit.setObjectName("gValueLineEdit")
        self.step5ParametersLayout.addWidget(self.gValueLineEdit, 3, 4, 1, 1)
        self.cStartLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.cStartLineEdit.setObjectName("cStartLineEdit")
        self.step5ParametersLayout.addWidget(self.cStartLineEdit, 2, 1, 1, 1)
        self.gLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.gLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.gLabel.setObjectName("gLabel")
        self.step5ParametersLayout.addWidget(self.gLabel, 3, 0, 1, 1)
        self.cStopLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.cStopLineEdit.setObjectName("cStopLineEdit")
        self.step5ParametersLayout.addWidget(self.cStopLineEdit, 2, 2, 1, 1)
        self.stepLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.stepLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.stepLabel.setObjectName("stepLabel")
        self.step5ParametersLayout.addWidget(self.stepLabel, 1, 3, 1, 1)
        self.optimizeSVMBut = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.optimizeSVMBut.setObjectName("optimizeSVMBut")
        self.step5ParametersLayout.addWidget(self.optimizeSVMBut, 4, 0, 1, 5)
        self.step5Layout.addLayout(self.step5ParametersLayout)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/Logos/LogoClaro_comLogo_w580.png"))
        self.label.setObjectName("label")
        self.step5Layout.addWidget(self.label)
        self.gridLayout_2.addLayout(self.step5Layout, 5, 0, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_2.addWidget(self.line_5, 5, 1, 1, 1)
        self.rocCurveLayout = QtWidgets.QGridLayout()
        self.rocCurveLayout.setObjectName("rocCurveLayout")
        self.loadSVMLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.loadSVMLabel.setObjectName("loadSVMLabel")
        self.rocCurveLayout.addWidget(self.loadSVMLabel, 1, 0, 1, 1)
        self.loadSVMLineEdit = ClickQLineEdit(self.scrollAreaWidgetContents)
        self.loadSVMLineEdit.setObjectName("loadSVMLineEdit")
        self.rocCurveLayout.addWidget(self.loadSVMLineEdit, 1, 1, 1, 1)
        self.generateROCBut = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.generateROCBut.setObjectName("generateROCBut")
        self.rocCurveLayout.addWidget(self.generateROCBut, 2, 0, 1, 2)
        self.ROCWidget = ROCWidget(self.scrollAreaWidgetContents)
        self.ROCWidget.setMinimumSize(QtCore.QSize(200, 200))
        self.ROCWidget.setObjectName("ROCWidget")
        self.rocCurveLayout.addWidget(self.ROCWidget, 0, 0, 1, 2)
        self.gridLayout_2.addLayout(self.rocCurveLayout, 5, 2, 1, 3)
        spacerItem6 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem6, 6, 0, 1, 5)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(trainingWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(trainingWindow)
        trainingWindow.setTabOrder(self.scrollArea, self.saveParametersBut)
        trainingWindow.setTabOrder(self.saveParametersBut, self.loadParametersBut)
        trainingWindow.setTabOrder(self.loadParametersBut, self.saveSpikes1LineEdit)
        trainingWindow.setTabOrder(self.saveSpikes1LineEdit, self.detectSpikes1But)
        trainingWindow.setTabOrder(self.detectSpikes1But, self.saveSpikes2LineEdit)
        trainingWindow.setTabOrder(self.saveSpikes2LineEdit, self.detectSpikes2But)
        trainingWindow.setTabOrder(self.detectSpikes2But, self.loadSpikes1LineEdit)
        trainingWindow.setTabOrder(self.loadSpikes1LineEdit, self.verifySpikes1But)
        trainingWindow.setTabOrder(self.verifySpikes1But, self.loadSpikes2LineEdit)
        trainingWindow.setTabOrder(self.loadSpikes2LineEdit, self.verifySpikes2But)
        trainingWindow.setTabOrder(self.verifySpikes2But, self.saveFeatures1LineEdit)
        trainingWindow.setTabOrder(self.saveFeatures1LineEdit, self.saveFeatures2LineEdit)
        trainingWindow.setTabOrder(self.saveFeatures2LineEdit, self.saveFilterLineEdit)
        trainingWindow.setTabOrder(self.saveFilterLineEdit, self.saveRescaleLineEdit)
        trainingWindow.setTabOrder(self.saveRescaleLineEdit, self.numberFeaturesLineEdit)
        trainingWindow.setTabOrder(self.numberFeaturesLineEdit, self.extractFeaturesBut)
        trainingWindow.setTabOrder(self.extractFeaturesBut, self.loadFeatures1LineEdit)
        trainingWindow.setTabOrder(self.loadFeatures1LineEdit, self.loadFeatures2LineEdit)
        trainingWindow.setTabOrder(self.loadFeatures2LineEdit, self.trainingNumberSamplesFish1LineEdit)
        trainingWindow.setTabOrder(self.trainingNumberSamplesFish1LineEdit, self.trainingProbabilityFish1LineEdit)
        trainingWindow.setTabOrder(self.trainingProbabilityFish1LineEdit, self.trainingSaveFish1LineEdit)
        trainingWindow.setTabOrder(self.trainingSaveFish1LineEdit, self.trainingLoadFish1LineEdit)
        trainingWindow.setTabOrder(self.trainingLoadFish1LineEdit, self.crossNumberSamplesFish1LineEdit)
        trainingWindow.setTabOrder(self.crossNumberSamplesFish1LineEdit, self.crossProbabilityFish1LineEdit)
        trainingWindow.setTabOrder(self.crossProbabilityFish1LineEdit, self.crossSaveFish1LineEdit)
        trainingWindow.setTabOrder(self.crossSaveFish1LineEdit, self.crossLoadFish1LineEdit)
        trainingWindow.setTabOrder(self.crossLoadFish1LineEdit, self.testingNumberSamplesFish1LineEdit)
        trainingWindow.setTabOrder(self.testingNumberSamplesFish1LineEdit, self.testingProbabilityFish1LineEdit)
        trainingWindow.setTabOrder(self.testingProbabilityFish1LineEdit, self.testingSaveFish1LineEdit)
        trainingWindow.setTabOrder(self.testingSaveFish1LineEdit, self.testingLoadFish1LineEdit)
        trainingWindow.setTabOrder(self.testingLoadFish1LineEdit, self.sliceFish1But)
        trainingWindow.setTabOrder(self.sliceFish1But, self.tabWidget)
        trainingWindow.setTabOrder(self.tabWidget, self.trainingNumberSamplesFish2LineEdit)
        trainingWindow.setTabOrder(self.trainingNumberSamplesFish2LineEdit, self.trainingProbabilityFish2LineEdit)
        trainingWindow.setTabOrder(self.trainingProbabilityFish2LineEdit, self.trainingSaveFish2LineEdit)
        trainingWindow.setTabOrder(self.trainingSaveFish2LineEdit, self.trainingLoadFish2LineEdit)
        trainingWindow.setTabOrder(self.trainingLoadFish2LineEdit, self.crossNumberSamplesFish2LineEdit)
        trainingWindow.setTabOrder(self.crossNumberSamplesFish2LineEdit, self.crossProbabilityFish2LineEdit)
        trainingWindow.setTabOrder(self.crossProbabilityFish2LineEdit, self.crossSaveFish2LineEdit)
        trainingWindow.setTabOrder(self.crossSaveFish2LineEdit, self.crossLoadFish2LineEdit)
        trainingWindow.setTabOrder(self.crossLoadFish2LineEdit, self.testingNumberSamplesFish2LineEdit)
        trainingWindow.setTabOrder(self.testingNumberSamplesFish2LineEdit, self.testingProbabilityFish2LineEdit)
        trainingWindow.setTabOrder(self.testingProbabilityFish2LineEdit, self.testingSaveFish2LineEdit)
        trainingWindow.setTabOrder(self.testingSaveFish2LineEdit, self.testingLoadFish2LineEdit)
        trainingWindow.setTabOrder(self.testingLoadFish2LineEdit, self.sliceFish2But)
        trainingWindow.setTabOrder(self.sliceFish2But, self.defaultSVMValuesBut)
        trainingWindow.setTabOrder(self.defaultSVMValuesBut, self.cStartLineEdit)
        trainingWindow.setTabOrder(self.cStartLineEdit, self.cStopLineEdit)
        trainingWindow.setTabOrder(self.cStopLineEdit, self.cStepLineEdit)
        trainingWindow.setTabOrder(self.cStepLineEdit, self.cValueLineEdit)
        trainingWindow.setTabOrder(self.cValueLineEdit, self.gStartLineEdit)
        trainingWindow.setTabOrder(self.gStartLineEdit, self.gStopLineEdit)
        trainingWindow.setTabOrder(self.gStopLineEdit, self.gStepLineEdit)
        trainingWindow.setTabOrder(self.gStepLineEdit, self.gValueLineEdit)
        trainingWindow.setTabOrder(self.gValueLineEdit, self.optimizeSVMBut)
        trainingWindow.setTabOrder(self.optimizeSVMBut, self.saveSVMLineEdit)
        trainingWindow.setTabOrder(self.saveSVMLineEdit, self.trainSVMBut)
        trainingWindow.setTabOrder(self.trainSVMBut, self.loadSVMLineEdit)
        trainingWindow.setTabOrder(self.loadSVMLineEdit, self.generateROCBut)

    def retranslateUi(self, trainingWindow):
        _translate = QtCore.QCoreApplication.translate
        trainingWindow.setWindowTitle(_translate("trainingWindow", "gymnotools - Training"))
        self.step1TitleLabel.setText(_translate("trainingWindow", "1. Calculate Hilbert Transform >"))
        self.lowCutoffLineEdit.setText(_translate("trainingWindow", "20"))
        self.gmeanLabel.setText(_translate("trainingWindow", "<html><head/><body><p align=\"center\">Geometric mean kernel size:</p></body></html>"))
        self.filterLabel.setText(_translate("trainingWindow", "Band-pass filter parameters:"))
        self.SaveLoadHilbLabel.setText(_translate("trainingWindow", "Save Hilbert Transform"))
        self.cutoffLabel.setText(_translate("trainingWindow", "Low/High cutoff (Hz):"))
        self.highCutoffLineEdit.setText(_translate("trainingWindow", "1000"))
        self.tapsLineEdit.setText(_translate("trainingWindow", "10001"))
        self.hilb2But.setText(_translate("trainingWindow", "Calculate Hilbert"))
        self.tapsLabel.setText(_translate("trainingWindow", "Number of taps:"))
        self.hilb1But.setText(_translate("trainingWindow", "Calculate Hilbert"))
        self.loadTSLabel.setText(_translate("trainingWindow", "Load timeseries data:"))
        self.spikeParametersFish2Label.setText(_translate("trainingWindow", "Fish 2"))
        self.hilbLabel.setText(_translate("trainingWindow", "Hilbert Transform"))
        self.spikeParametersFish1Label.setText(_translate("trainingWindow", "Fish 1"))
        self.gmeanLineEdit.setText(_translate("trainingWindow", "31"))
        self.saveParametersBut.setText(_translate("trainingWindow", "Save parameters"))
        self.loadParametersBut.setText(_translate("trainingWindow", "Load parameters"))
        self.step2TitleLabel.setText(_translate("trainingWindow", "2. Detect Spikes >"))
        self.onlyAboveLineEdit.setText(_translate("trainingWindow", "0.100"))
        self.toleranceLabel.setText(_translate("trainingWindow", "Minimum distance (ms):"))
        self.detectFish2Label.setText(_translate("trainingWindow", "Fish 2"))
        self.subSampLineEdit.setText(_translate("trainingWindow", "3"))
        self.thresholdLevelLabel.setText(_translate("trainingWindow", "Load hilbert File:"))
        self.verifySpikes1But.setText(_translate("trainingWindow", "Verify detection"))
        self.waveletLabel.setText(_translate("trainingWindow", "Min/Max/Step wavelet parameters:"))
        self.loadSpikesLabel.setText(_translate("trainingWindow", "Load spikes file:"))
        self.detectSpikes2But.setText(_translate("trainingWindow", "Detect Spikes"))
        self.verifySpikes2But.setText(_translate("trainingWindow", "Verify detection"))
        self.detectSpikes1But.setText(_translate("trainingWindow", "Detect Spikes"))
        self.subsampLabel.setText(_translate("trainingWindow", "Subsamp Hilbert:"))
        self.peakLabel.setText(_translate("trainingWindow", "Peak detection Order:"))
        self.detectFish1Label.setText(_translate("trainingWindow", "Fish 1"))
        self.minWaveletLineEdit.setText(_translate("trainingWindow", "12"))
        self.maxWaveletLineEdit.setText(_translate("trainingWindow", "120"))
        self.stepWaveletLineEdit.setText(_translate("trainingWindow", "0.1"))
        self.peakLineEdit.setText(_translate("trainingWindow", "15"))
        self.toleranceLineEdit.setText(_translate("trainingWindow", "0.5"))
        self.minHilbLabel.setText(_translate("trainingWindow", "Minimum Hilbert (V):"))
        self.onlyAboveLabel.setText(_translate("trainingWindow", "Only output spikes above (V):"))
        self.saveSpikesLabel.setText(_translate("trainingWindow", "Save detected spikes as: "))
        self.minHilbLineEdit.setText(_translate("trainingWindow", "0.060"))
        self.step3TitleLabel.setText(_translate("trainingWindow", "3. Rescale and extract features >"))
        self.saveRescaleLabel.setText(_translate("trainingWindow", "Save rescale as:"))
        self.numberFeaturesLabel.setText(_translate("trainingWindow", "Number of features: "))
        self.saveFeaturesLabel.setText(_translate("trainingWindow", "Save features as:"))
        self.loadFeaturesLabel.setText(_translate("trainingWindow", "Load features file: "))
        self.featuresFish1Label.setText(_translate("trainingWindow", "Fish 1"))
        self.featuresFish2Label.setText(_translate("trainingWindow", "Fish 2"))
        self.saveFilterLabel.setText(_translate("trainingWindow", "Save filter as:"))
        self.numberFeaturesLineEdit.setText(_translate("trainingWindow", "20"))
        self.extractFeaturesBut.setText(_translate("trainingWindow", "Extract features"))
        self.step4TitleLabel.setText(_translate("trainingWindow", "4. Slice series to make training, cross validation and testing sets >"))
        self.numberSamplesFish1Label.setText(_translate("trainingWindow", "Number of samples"))
        self.probabilityFish1Label.setText(_translate("trainingWindow", "Probability of selection"))
        self.saveSlicesFish1Label.setText(_translate("trainingWindow", "Save as:"))
        self.loadSlicesFish1Label.setText(_translate("trainingWindow", "Load slice file:"))
        self.trainingFish1Label.setText(_translate("trainingWindow", "Training set (About 10000 samples):"))
        self.crossValidationFish1Label.setText(_translate("trainingWindow", "Cross validation set (About prob. 0.3):"))
        self.testingFish1Label.setText(_translate("trainingWindow", "Testing set: "))
        self.sliceFish1But.setText(_translate("trainingWindow", "Slice"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFish1), _translate("trainingWindow", "Fish 1"))
        self.numberSamplesFish2Label.setText(_translate("trainingWindow", "Number of samples"))
        self.probabilityFish2Label.setText(_translate("trainingWindow", "Probability of selection"))
        self.saveSlicesFish2Label.setText(_translate("trainingWindow", "Save as:"))
        self.loadSlicesFish2Label.setText(_translate("trainingWindow", "Load slice file:"))
        self.trainingFish2Label.setText(_translate("trainingWindow", "Training set (About 10000 samples):"))
        self.crossValidationFish2Label.setText(_translate("trainingWindow", "Cross validation set (About prob. 0.3):"))
        self.testingFish2Label.setText(_translate("trainingWindow", "Testing set: "))
        self.sliceFish2But.setText(_translate("trainingWindow", "Slice"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFish2), _translate("trainingWindow", "Fish 2"))
        self.step5TitleLabel.setText(_translate("trainingWindow", "5. Train SVM >"))
        self.defaultSVMValuesBut.setText(_translate("trainingWindow", "Default values"))
        self.saveSVMLabel.setText(_translate("trainingWindow", "Save SVM model as: "))
        self.valueLabel.setText(_translate("trainingWindow", "Selected value"))
        self.trainSVMBut.setText(_translate("trainingWindow", "Train SVM"))
        self.startLabel.setText(_translate("trainingWindow", "Start"))
        self.stopLabel.setText(_translate("trainingWindow", "Stop"))
        self.gStopLineEdit.setText(_translate("trainingWindow", "3.0"))
        self.cStepLineEdit.setText(_translate("trainingWindow", "2.0"))
        self.gStartLineEdit.setText(_translate("trainingWindow", "-15.0"))
        self.gStepLineEdit.setText(_translate("trainingWindow", "2.0"))
        self.cLabel.setText(_translate("trainingWindow", "SVM C Parameter: "))
        self.cStartLineEdit.setText(_translate("trainingWindow", "-5.0"))
        self.gLabel.setText(_translate("trainingWindow", "SVM Gamma Parameter: "))
        self.cStopLineEdit.setText(_translate("trainingWindow", "15.0"))
        self.stepLabel.setText(_translate("trainingWindow", "Step"))
        self.optimizeSVMBut.setText(_translate("trainingWindow", "Optimize Parameters"))
        self.loadSVMLabel.setText(_translate("trainingWindow", "Load SVM model: "))
        self.generateROCBut.setText(_translate("trainingWindow", "Generate ROC Curve"))

from gui.ROCAux import ROCWidget
from gui.clickAux import ClickQLabel, ClickQLineEdit
from gui import resource_rc
